=== WoltLab/WCF/XSD/acpmenu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- The file "acpmenu.xsd" is used for xml-files which installs, updates or deletes acp-menu items.  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
        
        <!-- include types -->
        <xs:include schemaLocation="types.xsd" />
        
        <!-- Represents the data-node. -->
        <xs:element name="data">
                <xs:complexType>
                        <xs:all>
                                <xs:element name="import" type="import" minOccurs="0" />
                                <xs:element name="delete" type="delete" minOccurs="0" />
                        </xs:all>
                </xs:complexType>
        </xs:element>
        
          <!-- Represents the import-node. -->
        <xs:complexType name="import">
                <xs:sequence>
                        <xs:element name="acpmenuitem" type="acpmenuitem_import" maxOccurs="unbounded" />
                </xs:sequence>
        </xs:complexType>
        
        <!-- Represents the delete-node. -->
        <xs:complexType name="delete">
                <xs:sequence>
                        <xs:element name="acpmenuitem" type="acpmenuitem_delete" maxOccurs="unbounded" />
                </xs:sequence>
        </xs:complexType>
        
        <!-- Represents an acpmenuitem which will be deleted. The node needs the attribute "name". -->
        <xs:complexType name="acpmenuitem_delete">
                <xs:attribute name="name" type="woltlab_varchar" use="required" />
        </xs:complexType>
        
        <!-- Represents an acpmenuitem which will be installed or updated. Extends the type "acpmenuitem_delete". -->
        <xs:complexType name="acpmenuitem_import">
                <xs:complexContent>
                        <xs:extension base="acpmenuitem_delete">
                                    <xs:all>
                                        <xs:element name="parent" type="woltlab_varchar_nullable" minOccurs="0" />
                                        <xs:element name="link" type="woltlab_varchar_nullable" minOccurs="0" />
                                        <xs:element name="showorder" type="xs:unsignedInt" minOccurs="0" />
                                        <xs:element name="permissions" type="xs:string" minOccurs="0" />
                                        <xs:element name="options" type="xs:string" minOccurs="0" />
                                </xs:all>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/acpmenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/maelstrom/acpMenu.xsd">
	<import>
		<acpmenuitem name="wcf.acp.menu.link.system">
			<showorder>1</showorder>
		</acpmenuitem>
		
		<!-- options -->
		<acpmenuitem name="wcf.acp.menu.link.option">
			<parent>wcf.acp.menu.link.system</parent>
			<showorder>1</showorder>
			<permissions>admin.system.canEditOption</permissions>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.option.category">
			<parent>wcf.acp.menu.link.option</parent>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.option.management">
			<parent>wcf.acp.menu.link.option</parent>
			<showorder>2</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.option.importAndExport">
			<parent>wcf.acp.menu.link.option.management</parent>
			<showorder>1</showorder>
			<link>index.php?form=OptionImport</link>
		</acpmenuitem>
		<!-- /options -->
		
		<!-- packages -->
		<acpmenuitem name="wcf.acp.menu.link.package">
			<parent>wcf.acp.menu.link.system</parent>
			<showorder>2</showorder>
			<permissions>admin.system.package.canInstallPackage,admin.system.package.canUpdatePackage,admin.system.package.canUninstallPackage,admin.system.package.canEditServer</permissions>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.package.management">
			<parent>wcf.acp.menu.link.package</parent>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.package.list">
			<link>index.php?page=PackageList</link>
			<parent>wcf.acp.menu.link.package.management</parent>
			<permissions>admin.system.package.canUpdatePackage,admin.system.package.canUninstallPackage</permissions>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.package.install">
			<link>index.php?form=PackageStartInstall&amp;action=install</link>
			<parent>wcf.acp.menu.link.package.management</parent>
			<permissions>admin.system.package.canInstallPackage</permissions>
			<showorder>2</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.package.update">
			<parent>wcf.acp.menu.link.package</parent>
			<showorder>2</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.package.autoupdate">
			<link>index.php?page=PackageAutoUpdateList</link>
			<parent>wcf.acp.menu.link.package.update</parent>
			<permissions>admin.system.package.canUpdatePackage</permissions>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.package.database">
			<link>index.php?form=PackageUpdateSearch</link>
			<parent>wcf.acp.menu.link.package.update</parent>
			<permissions>admin.system.package.canInstallPackage,admin.system.package.canUpdatePackage</permissions>
			<showorder>2</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.package.server">
			<parent>wcf.acp.menu.link.package</parent>
			<showorder>3</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.package.server.list">
			<link>index.php?page=UpdateServerList</link>
			<parent>wcf.acp.menu.link.package.server</parent>
			<permissions>admin.system.package.canEditServer</permissions>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.package.server.add">
			<link>index.php?form=UpdateServerAdd</link>
			<parent>wcf.acp.menu.link.package.server</parent>
			<permissions>admin.system.package.canEditServer</permissions>
			<showorder>2</showorder>
		</acpmenuitem>
		<!-- /packages -->	
		
		<!-- cronjobs -->
		<acpmenuitem name="wcf.acp.menu.link.cronjob">
			<parent>wcf.acp.menu.link.system</parent>
			<showorder>3</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.cronjob.list">
			<link>index.php?page=CronjobList</link>
			<parent>wcf.acp.menu.link.cronjob</parent>
			<permissions>admin.system.cronjobs.canEditCronjob,admin.system.cronjob.canDeleteCronjob,admin.system.cronjobs.canEnableDisableCronjob</permissions>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.cronjob.add">
			<link>index.php?form=CronjobAdd</link>
			<parent>wcf.acp.menu.link.cronjob</parent>
			<permissions>admin.system.cronjob.canAddCronjob</permissions>
			<showorder>2</showorder>
		</acpmenuitem>
		<!-- /cronjobs -->
		
		<!-- log -->
		<acpmenuitem name="wcf.acp.menu.link.log">
			<parent>wcf.acp.menu.link.system</parent>
			<showorder>4</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.log.session">
			<link>index.php?page=ACPSessionLogList</link>
			<parent>wcf.acp.menu.link.log</parent>
			<permissions>admin.system.canViewLog</permissions>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.log.cache">
			<link>index.php?page=CacheList</link>
			<parent>wcf.acp.menu.link.log</parent>
			<permissions>admin.system.canViewLog</permissions>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.log.cronjob">
			<link>index.php?page=CronjobLogList</link>
			<parent>wcf.acp.menu.link.log</parent>
			<permissions>admin.system.cronjob.canEditCronjob,admin.system.cronjob.canDeleteCronjob</permissions>
		</acpmenuitem>
		<!-- /log -->
		
		<acpmenuitem name="wcf.acp.menu.link.user">
			<showorder>2</showorder>
		</acpmenuitem>
		
		<!-- users -->
		<acpmenuitem name="wcf.acp.menu.link.user.management">
			<parent>wcf.acp.menu.link.user</parent>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.user.management.general">
			<parent>wcf.acp.menu.link.user.management</parent>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.user.list">
			<link>index.php?page=UserList</link>
			<parent>wcf.acp.menu.link.user.management.general</parent>
			<permissions>admin.user.canSearchUser</permissions>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.user.search">
			<link>index.php?form=UserSearch</link>
			<parent>wcf.acp.menu.link.user.management.general</parent>
			<permissions>admin.user.canSearchUser</permissions>
			<showorder>2</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.user.add">
			<link>index.php?form=UserAdd</link>
			<parent>wcf.acp.menu.link.user.management.general</parent>
			<permissions>admin.user.canAddUser</permissions>
			<showorder>3</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.user.management.additional">
			<parent>wcf.acp.menu.link.user.management</parent>
			<showorder>2</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.user.massProcessing">
			<link>index.php?form=UsersMassProcessing</link>
			<parent>wcf.acp.menu.link.user.management.additional</parent>
			<permissions>admin.user.canEditUser,admin.user.canDeleteUser,admin.user.canMailUser</permissions>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.user.mail">
			<link>index.php?form=UserMail&amp;action=all</link>
			<parent>wcf.acp.menu.link.user.management.additional</parent>
			<permissions>admin.user.canMailUser</permissions>
			<showorder>2</showorder>
		</acpmenuitem>
		<!-- /users -->
		
		<!-- user groups -->
		<acpmenuitem name="wcf.acp.menu.link.group">
			<parent>wcf.acp.menu.link.user</parent>
			<showorder>2</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.group.general">
			<parent>wcf.acp.menu.link.group</parent>
			<showorder>1</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.group.list">
			<link>index.php?page=UserGroupList</link>
			<parent>wcf.acp.menu.link.group.general</parent>
			<permissions>admin.user.canEditGroup,admin.user.canDeleteGroup</permissions>
			<showorder>1</showorder>
		</acpmenuitem>	
		
		<acpmenuitem name="wcf.acp.menu.link.group.add">
			<link>index.php?form=UserGroupAdd</link>
			<parent>wcf.acp.menu.link.group.general</parent>
			<permissions>admin.user.canAddGroup</permissions>
			<showorder>2</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.group.additional">
			<parent>wcf.acp.menu.link.group</parent>
			<showorder>2</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.group.mail">
			<link>index.php?form=UserMail&amp;action=group</link>
			<parent>wcf.acp.menu.link.group.additional</parent>
			<permissions>admin.user.canMailUser</permissions>
			<showorder>1</showorder>
		</acpmenuitem>
		<!-- user groups -->
		
		<acpmenuitem name="wcf.acp.menu.link.display">
			<showorder>3</showorder>
		</acpmenuitem>
		
		<acpmenuitem name="wcf.acp.menu.link.content">
			<showorder>4</showorder>
		</acpmenuitem>
	</import>
</data>
