=== WoltLab/WCF/XSD/bbcode.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is used for xml-files which install, update or delete page menu items. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="bbcode" type="bbcode_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- delete element -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="bbcode" type="bbcode_delete" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- deleted page menu item element -->
	<xs:complexType name="bbcode_delete">
		<xs:attribute name="name" type="woltlab_varchar" use="required" />
	</xs:complexType>
	
	<!-- imported/updated page menu item element -->
	<xs:complexType name="bbcode_import">
		<xs:complexContent>
			<xs:extension base="bbcode_delete">
				<xs:all>
					<xs:element name="htmlopen" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="htmlclose" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="allowedchildren" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="classname" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="attributes" type="attributes_element" minOccurs="0" />
					<xs:element name="sourcecode" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="wysiwygicon" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="wysiwyg" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="buttonlabel" type="woltlab_varchar_nullable" minOccurs="0" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="attributes_element">
		<xs:sequence>
			<xs:element name="attribute" type="attribute_element" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="attribute_element">
		<xs:complexContent>
			<xs:extension base="attribute_element_basic">
				<xs:all>
					<xs:element name="required" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="usetext" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="validationpattern" type="xs:string" minOccurs="0" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="attribute_element_basic">
		<xs:attribute name="name" type="xs:unsignedInt" use="required" />
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/bbcode.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/5.4/bbcode.xsd">
	<import>
		<bbcode name="b">
			<htmlopen><![CDATA[b]]></htmlopen>
			<htmlclose><![CDATA[b]]></htmlclose>
		</bbcode>
		<bbcode name="i">
			<htmlopen><![CDATA[i]]></htmlopen>
			<htmlclose><![CDATA[i]]></htmlclose>
		</bbcode>
		<bbcode name="u">
			<htmlopen><![CDATA[span style="text-decoration: underline"]]></htmlopen>
			<htmlclose><![CDATA[span]]></htmlclose>
		</bbcode>
		<bbcode name="s">
			<htmlopen><![CDATA[s]]></htmlopen>
			<htmlclose><![CDATA[s]]></htmlclose>
		</bbcode>
		<bbcode name="sub">
			<htmlopen><![CDATA[sub]]></htmlopen>
			<htmlclose><![CDATA[sub]]></htmlclose>
		</bbcode>
		<bbcode name="sup">
			<htmlopen><![CDATA[sup]]></htmlopen>
			<htmlclose><![CDATA[sup]]></htmlclose>
		</bbcode>
		<bbcode name="email">
			<classname>wcf\system\bbcode\EmailBBCode</classname>
			<attributes>
				<attribute name="0">
					<validationpattern><![CDATA[^[^\s]+@[^\s]+$]]></validationpattern>
					<required>1</required>
					<usetext>1</usetext>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="color">
			<htmlopen><![CDATA[span]]></htmlopen>
			<htmlclose><![CDATA[span]]></htmlclose>
			<attributes>
				<attribute name="0">
					<html><![CDATA[style="color: %s"]]></html>
					<validationpattern><![CDATA[^(#([0-9a-f]{3}|[0-9a-f]{6})|[a-z]+)$]]></validationpattern>
					<required>1</required>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="size">
			<htmlopen><![CDATA[span]]></htmlopen>
			<htmlclose><![CDATA[span]]></htmlclose>
			<attributes>
				<attribute name="0">
					<html><![CDATA[style="font-size: %dpt"]]></html>
					<validationpattern><![CDATA[^([89]{1}|[1-3]{1}[0-9]{1})$]]></validationpattern>
					<required>1</required>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="font">
			<htmlopen><![CDATA[span]]></htmlopen>
			<htmlclose><![CDATA[span]]></htmlclose>
			<attributes>
				<attribute name="0">
					<html><![CDATA[style="font-family: %s"]]></html>
					<validationpattern><![CDATA[^[^"';}\(\)]*$]]></validationpattern>
					<required>1</required>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="align">
			<htmlopen><![CDATA[div]]></htmlopen>
			<htmlclose><![CDATA[div]]></htmlclose>
			<isBlockElement>1</isBlockElement>
			<attributes>
				<attribute name="0">
					<html><![CDATA[class="text-%s"]]></html>
					<validationpattern><![CDATA[^(left|right|center|justify)$]]></validationpattern>
					<required>1</required>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="quote">
			<isBlockElement>1</isBlockElement>
			<buttonlabel>wcf.editor.button.quote</buttonlabel>
			<wysiwygicon solid="true">quote-left</wysiwygicon>
			<attributes>
				<attribute name="0"/>
				<attribute name="1"/>
			</attributes>
		</bbcode>
		<bbcode name="code">
			<isBlockElement>1</isBlockElement>
			<sourcecode>1</sourcecode>
			<buttonlabel>wcf.editor.button.code</buttonlabel>
			<wysiwygicon>code</wysiwygicon>
			<attributes>
				<attribute name="0"/>
				<attribute name="1"/>
				<attribute name="2"/>
			</attributes>
		</bbcode>
		<bbcode name="img">
			<attributes>
				<attribute name="0">
					<validationpattern><![CDATA[^.+$]]></validationpattern>
					<required>1</required>
					<usetext>1</usetext>
				</attribute>
				<attribute name="1">
					<validationpattern><![CDATA[^(left|right|none)$]]></validationpattern>
				</attribute>
				<attribute name="2">
					<validationpattern><![CDATA[^\d+$]]></validationpattern>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="url">
			<attributes>
				<attribute name="0">
					<validationpattern><![CDATA[^.+$]]></validationpattern>
					<required>1</required>
					<usetext>1</usetext>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="list">
			<isBlockElement>1</isBlockElement>
			<attributes>
				<attribute name="0">
					<validationpattern><![CDATA[^(1|a|none|circle|square|disc|decimal|lower-roman|upper-roman|decimal-leading-zero|lower-greek|lower-latin|upper-latin|armenian|georgian)$]]></validationpattern>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="table">
			<isBlockElement>1</isBlockElement>
		</bbcode>
		<bbcode name="tr">
			<classname>wcf\system\bbcode\TrBBCode</classname>
			<isBlockElement>1</isBlockElement>
		</bbcode>
		<bbcode name="td">
			<classname>wcf\system\bbcode\TdBBCode</classname>
			<isBlockElement>1</isBlockElement>
		</bbcode>
		<bbcode name="media">
			<classname>wcf\system\bbcode\MediaBBCode</classname>
			<sourcecode>1</sourcecode>
		</bbcode>
		<bbcode name="spoiler">
			<isBlockElement>1</isBlockElement>
			<buttonlabel>wcf.editor.button.spoiler</buttonlabel>
			<wysiwygicon>eye-slash</wysiwygicon>
			<attributes>
				<attribute name="0"/>
			</attributes>
		</bbcode>
		<bbcode name="tt">
			<htmlopen><![CDATA[kbd]]></htmlopen>
			<htmlclose><![CDATA[kbd]]></htmlclose>
			<sourcecode>1</sourcecode>
			<buttonlabel>wcf.editor.button.inlineCode</buttonlabel>
			<wysiwygicon>terminal</wysiwygicon>
		</bbcode>
		<bbcode name="attach">
			<classname>wcf\system\bbcode\AttachmentBBCode</classname>
			<attributes>
				<attribute name="0">
					<validationpattern><![CDATA[^\d+$]]></validationpattern>
					<required>1</required>
					<usetext>1</usetext>
				</attribute>
				<attribute name="1">
					<validationpattern><![CDATA[^(left|right|none)$]]></validationpattern>
				</attribute>
				<attribute name="2">
					<validationpattern><![CDATA[^(\d+|true|false)$]]></validationpattern>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="wsm">
			<classname>wcf\system\bbcode\WoltLabSuiteMediaBBCode</classname>
			<isBlockElement>1</isBlockElement>
			<attributes>
				<attribute name="0">
					<validationpattern><![CDATA[^\d+$]]></validationpattern>
					<required>1</required>
				</attribute>
				<attribute name="1">
					<validationpattern><![CDATA[^(small|medium|large|original)$]]></validationpattern>
				</attribute>
				<attribute name="2">
					<validationpattern><![CDATA[^(left|right|none)$]]></validationpattern>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="wsp">
			<classname>wcf\system\bbcode\WoltLabSuitePageBBCode</classname>
			<attributes>
				<attribute name="0">
					<validationpattern><![CDATA[^\d+(?:#.+)?$]]></validationpattern>
					<required>1</required>
				</attribute>
				<attribute name="1">
					<usetext>1</usetext>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="user">
			<classname>wcf\system\bbcode\UserBBCode</classname>
			<sourcecode>1</sourcecode>
			<attributes>
				<attribute name="0">
					<validationpattern><![CDATA[^\d+$]]></validationpattern>
					<required>1</required>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="html">
			<isBlockElement>1</isBlockElement>
			<sourcecode>1</sourcecode>
			<buttonlabel>wcf.editor.button.woltlabHtml</buttonlabel>
			<wysiwygicon>file-code</wysiwygicon>
		</bbcode>
		<bbcode name="wsa">
			<classname>wcf\system\bbcode\WoltLabSuiteArticleBBCode</classname>
			<attributes>
				<attribute name="0">
					<validationpattern><![CDATA[^\d+$]]></validationpattern>
					<required>1</required>
					<usetext>1</usetext>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="group">
			<sourcecode>1</sourcecode>
			<classname>wcf\system\bbcode\GroupBBCode</classname>
			<attributes>
				<attribute name="0">
					<validationpattern><![CDATA[^\d+$]]></validationpattern>
					<required>1</required>
				</attribute>
			</attributes>
		</bbcode>
		<bbcode name="mark">
			<htmlopen><![CDATA[mark]]></htmlopen>
			<htmlclose><![CDATA[mark]]></htmlclose>
			<attributes>
				<attribute name="0">
					<html><![CDATA[class="%s"]]></html>
					<validationpattern><![CDATA[^marker-(info|error|success|warning)$]]></validationpattern>
					<required>1</required>
				</attribute>
			</attributes>
		</bbcode>
	</import>
</data>
