=== WoltLab/WCF/XSD/box.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is used for xml-files which install, update or delete boxes. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="box" type="box_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- delete element -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="box" type="box_delete" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- deleted box -->
	<xs:complexType name="box_delete">
		<xs:attribute name="identifier" type="woltlab_varchar" use="required" />
	</xs:complexType>
	
	<!-- imported/updated box -->
	<xs:complexType name="box_import">
		<xs:complexContent>
			<xs:extension base="box_delete">
				<xs:choice maxOccurs="unbounded">
					<xs:element name="boxType" minOccurs="1">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="html" />
								<xs:enumeration value="text" />
								<xs:enumeration value="tpl" />
								<xs:enumeration value="system" />
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="objectType" type="xs:string" minOccurs="0" />
					<xs:element name="position" type="xs:string" minOccurs="0" />
					<xs:element name="cssClassName" type="xs:string" minOccurs="0" />
					<xs:element name="showHeader" type="woltlab_boolean" minOccurs="1" />
					<xs:element name="visibleEverywhere" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="visibilityExceptions" type="visibilityExceptions_element" minOccurs="0" />
					<xs:element name="sortField" type="xs:string" minOccurs="0" />
					<xs:element name="sortOrder" minOccurs="1">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="ASC" />
								<xs:enumeration value="DESC" />
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="limit" type="xs:integer" minOccurs="0" />
					<xs:element name="content" type="content_element" minOccurs="1" />
					<xs:element name="name" type="name_element" minOccurs="1" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="content_element">
		<xs:all>
			<xs:element name="title" type="woltlab_varchar" minOccurs="1" />
			<xs:element name="content" type="xs:string" minOccurs="0" />
		</xs:all>
		<xs:attribute name="language" type="woltlab_varchar" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="visibilityExceptions_element">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="page" type="xs:string" minOccurs="1" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="name_element">
		<xs:simpleContent>
			<xs:extension base="woltlab_varchar">
				<xs:attribute name="language" type="woltlab_varchar" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/box.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/vortex/box.xsd">
	<import>
		<box identifier="com.woltlab.wcf.RecentActivity">
			<name language="de">Letzte Aktivitäten</name>
			<name language="en">Recent Activities</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.recentActivityList</objectType>
			<position>contentBottom</position>
			<showHeader>0</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			<visibilityExceptions>
				<page>com.woltlab.wcf.Dashboard</page>
			</visibilityExceptions>
			<limit>10</limit>
			
			<content language="de">
				<title>Letzte Aktivitäten</title>
			</content>
			<content language="en">
				<title>Recent Activities</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.RecentActivitySidebar">
			<name language="de">Letzte Aktivitäten (Sidebar)</name>
			<name language="en">Recent Activities (Sidebar)</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.recentActivityList</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			<visibilityExceptions>
				<page>com.woltlab.wcf.Dashboard</page>
			</visibilityExceptions>
			<limit>10</limit>
			
			<content language="de">
				<title>Letzte Aktivitäten</title>
			</content>
			<content language="en">
				<title>Recent Activities</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.PaidSubscriptions">
			<name language="de">Bezahlte Mitgliedschaften</name>
			<name language="en">Paid Subscriptions</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.paidSubscriptions</objectType>
			<position>contentBottom</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			
			<content language="de">
				<title>Bezahlte Mitgliedschaften</title>
			</content>
			<content language="en">
				<title>Paid Subscriptions</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.PaidSubscriptionsSidebar">
			<name language="de">Bezahlte Mitgliedschaften (Sidebar)</name>
			<name language="en">Paid Subscriptions (Sidebar)</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.paidSubscriptions</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			
			<content language="de">
				<title>Bezahlte Mitgliedschaften</title>
			</content>
			<content language="en">
				<title>Paid Subscriptions</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.RegisterButton">
			<name language="de">Registrierungs-Button</name>
			<name language="en">Register Button</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.registerButton</objectType>
			<position>sidebarRight</position>
			<showHeader>0</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			<!--<cssClassName></cssClassName> todo -->
			<visibilityExceptions>
				<page>com.woltlab.wcf.Dashboard</page>
			</visibilityExceptions>
			
			<content language="de">
				<title>Registrierung</title>
			</content>
			<content language="en">
				<title>Registration</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.SignedInAs">
			<name language="de">Angemeldet als</name>
			<name language="en">Signed In As</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.signedInAs</objectType>
			<position>sidebarRight</position>
			<showHeader>0</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			<visibilityExceptions>
				<page>com.woltlab.wcf.Dashboard</page>
			</visibilityExceptions>
			
			<!-- TODO: content title -->
		</box>
		
		<box identifier="com.woltlab.wcf.Statistics">
			<name language="de">Statistiken</name>
			<name language="en">Statistics</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.statistics</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			<visibilityExceptions>
				<page>com.woltlab.wcf.Dashboard</page>
			</visibilityExceptions>
			
			<content language="de">
				<title>Statistiken</title>
			</content>
			<content language="en">
				<title>Statistics</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.NewestMembers">
			<name language="de">Neueste Mitglieder</name>
			<name language="en">Newest Members</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.userList</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			<sortField>registrationDate</sortField>
			<sortOrder>DESC</sortOrder>
			
			<content language="de">
				<title>Neueste Mitglieder</title>
			</content>
			<content language="en">
				<title>Newest Members</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.MostActiveMembers">
			<name language="de">Aktivste Mitglieder</name>
			<name language="en">Most Active Members</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.userList</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			<sortField>activityPoints</sortField>
			<sortOrder>DESC</sortOrder>
			
			<content language="de">
				<title>Aktivste Mitglieder</title>
			</content>
			<content language="en">
				<title>Most Active Members</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.MostLikedMembers">
			<name language="de">Mitglieder mit den meisten Likes</name>
			<name language="en">Most Liked Members</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.userList</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			<sortField>likesReceived</sortField>
			<sortOrder>DESC</sortOrder>
			
			<content language="de">
				<title>Mitglieder mit den meisten Likes</title>
			</content>
			<content language="en">
				<title>Most Liked Members</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.TodaysBirthdays">
			<name language="de">Heutige Geburtstage</name>
			<name language="en">Today’s Birthdays</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.todaysBirthdays</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			
			<content language="de">
				<title>Heutige Geburtstage</title>
			</content>
			<content language="en">
				<title>Today’s Birthdays</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.TodaysFollowingBirthdays">
			<name language="de">Heutige Geburtstage von Nutzern, denen der Nutzer folgt</name>
			<name language="en">Today’s Birthdays of Users the User Follows</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.todaysFollowingBirthdays</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			
			<!-- TODO: content title -->
		</box>
		
		<box identifier="com.woltlab.wcf.UsersOnline">
			<name language="de">Benutzer online</name>
			<name language="en">Users Online</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.userOnlineList</objectType>
			<position>footerBoxes</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			
			<content language="de">
				<title>Benutzer online</title>
			</content>
			<content language="en">
				<title>Users Online</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.UsersOnlineSidebar">
			<name language="de">Benutzer online (Sidebar)</name>
			<name language="en">Users Online (Sidebar)</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.userOnlineList</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			
			<content language="de">
				<title>Benutzer online</title>
			</content>
			<content language="en">
				<title>Users Online</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.StaffOnline">
			<name language="de">Team-Mitglieder online</name>
			<name language="en">Staff-Members Online</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.staffOnlineList</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			
			<content language="de">
				<title>Team-Mitglieder online</title>
			</content>
			<content language="en">
				<title>Staff-Members Online</title>
			</content>
		</box>
		
		<box identifier="com.woltlab.wcf.FollowingsOnline">
			<name language="de">Benutzer online, denen der Nutzer folgt</name>
			<name language="en">Users Online the User Follows</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.followingsOnline</objectType>
			<position>sidebarRight</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			<limit>10</limit>
			
			<!-- TODO: content title -->
		</box>
		
		<box identifier="com.woltlab.wcf.PageComments">
			<name language="de">Seiten-Kommentare</name>
			<name language="en">Page Comments</name>
			<boxType>system</boxType>
			<objectType>com.woltlab.wcf.pageCommentList</objectType>
			<position>contentBottom</position>
			<showHeader>1</showHeader>
			<visibleEverywhere>0</visibleEverywhere>
			
			<content language="de">
				<title>Kommentare</title>
			</content>
			<content language="en">
				<title>Comments</title>
			</content>
		</box>
	</import>
</data>
