=== WoltLab/WCF/XSD/clipBoardAction.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- This file is used for xml files which install, update or delete clip board actions. -->
<xs:schema id="data" targetNamespace="http://www.woltlab.com" xmlns="http://www.woltlab.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
	<!-- action element -->
	<xs:element name="action">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="actionclassname" type="xs:string" minOccurs="0" />
				<xs:element name="showorder" type="xs:string" minOccurs="0" />
				<xs:element name="pages" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="page" nillable="true" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" form="unqualified" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="action" />
				<xs:element name="import">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="action" minOccurs="0" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="delete">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="action" minOccurs="0" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/clipBoardAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/maelstrom/clipBoardAction.xsd">
	<import>
		<action name="assignToGroup">
			<actionclassname><![CDATA[wcf\system\clipboard\action\UserClipboardAction]]></actionclassname>
			<showorder>1</showorder>
			<pages>
				<page><![CDATA[wcf\acp\page\UserListPage]]></page>
			</pages>
		</action>
		
		<action name="sendMail">
			<actionclassname><![CDATA[wcf\system\clipboard\action\UserClipboardAction]]></actionclassname>
			<showorder>2</showorder>
			<pages>
				<page><![CDATA[wcf\acp\page\UserListPage]]></page>
			</pages>
		</action>

		<action name="delete">
			<actionclassname><![CDATA[wcf\system\clipboard\action\UserClipboardAction]]></actionclassname>
			<showorder>3</showorder>
			<pages>
				<page><![CDATA[wcf\acp\page\UserListPage]]></page>
			</pages>
		</action>

		<action name="exportMailAddress">
			<actionclassname><![CDATA[wcf\system\clipboard\action\UserClipboardAction]]></actionclassname>
			<showorder>4</showorder>
			<pages>
				<page><![CDATA[wcf\acp\page\UserListPage]]></page>
			</pages>
		</action>
	</import>
</data>

=== WoltLab/WCF/com.woltlab.wcf/clipboardAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/2019/clipboardAction.xsd">
	<import>
		<!-- com.woltlab.wcf.user -->
		<action name="assignToGroup">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>1</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="delete">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>2</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="deleteUserContent">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>3</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="ban">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>4</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="merge">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>5</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="enable">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>6</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="confirmEmail">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>7</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="unconfirmEmail">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>8</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="resendActivationMail">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>9</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="sendMail">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>10</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="exportMailAddress">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>11</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="sendNewPassword">
			<actionclassname>wcf\system\clipboard\action\UserClipboardAction</actionclassname>
			<showorder>12</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<action name="revertContentChanges">
			<actionclassname>wcf\system\clipboard\action\UserContentClipboardAction</actionclassname>
			<showorder>13</showorder>
			<pages>
				<page>wcf\acp\page\UserListPage</page>
			</pages>
		</action>
		<!-- /com.woltlab.wcf.user -->
		<!-- com.woltlab.wcf.tag -->
		<action name="delete">
			<actionclassname>wcf\system\clipboard\action\TagClipboardAction</actionclassname>
			<showorder>1</showorder>
			<pages>
				<page>wcf\acp\page\TagListPage</page>
			</pages>
		</action>
		<action name="setAsSynonyms">
			<actionclassname>wcf\system\clipboard\action\TagClipboardAction</actionclassname>
			<showorder>2</showorder>
			<pages>
				<page>wcf\acp\page\TagListPage</page>
			</pages>
		</action>
		<!-- com.woltlab.wcf.tag -->
		<!-- com.woltlab.wcf.media -->
		<action name="insert">
			<actionclassname>wcf\system\clipboard\action\MediaClipboardAction</actionclassname>
			<showorder>1</showorder>
			<pages>
				<page>menuManagerDialog-editor</page>
			</pages>
		</action>
		<action name="delete">
			<actionclassname>wcf\system\clipboard\action\MediaClipboardAction</actionclassname>
			<showorder>2</showorder>
			<pages>
				<page>wcf\acp\page\MediaListPage</page>
				<page>menuManagerDialog-editor</page>
				<page>menuManagerDialog-select</page>
			</pages>
		</action>
		<action name="setCategory">
			<actionclassname>wcf\system\clipboard\action\MediaClipboardAction</actionclassname>
			<showorder>3</showorder>
			<pages>
				<page>wcf\acp\page\MediaListPage</page>
				<page>menuManagerDialog-editor</page>
				<page>menuManagerDialog-select</page>
			</pages>
		</action>
		<!-- /com.woltlab.wcf.media -->
		<!-- com.woltlab.wcf.article -->
		<action name="trash">
			<actionclassname>wcf\system\clipboard\action\ArticleClipboardAction</actionclassname>
			<showorder>1</showorder>
			<pages>
				<page>wcf\acp\page\ArticleListPage</page>
			</pages>
		</action>
		<action name="delete">
			<actionclassname>wcf\system\clipboard\action\ArticleClipboardAction</actionclassname>
			<showorder>2</showorder>
			<pages>
				<page>wcf\acp\page\ArticleListPage</page>
			</pages>
		</action>
		<action name="restore">
			<actionclassname>wcf\system\clipboard\action\ArticleClipboardAction</actionclassname>
			<showorder>3</showorder>
			<pages>
				<page>wcf\acp\page\ArticleListPage</page>
			</pages>
		</action>
		<action name="unpublish">
			<actionclassname>wcf\system\clipboard\action\ArticleClipboardAction</actionclassname>
			<showorder>4</showorder>
			<pages>
				<page>wcf\acp\page\ArticleListPage</page>
			</pages>
		</action>
		<action name="publish">
			<actionclassname>wcf\system\clipboard\action\ArticleClipboardAction</actionclassname>
			<showorder>5</showorder>
			<pages>
				<page>wcf\acp\page\ArticleListPage</page>
			</pages>
		</action>
		<action name="setCategory">
			<actionclassname>wcf\system\clipboard\action\ArticleClipboardAction</actionclassname>
			<showorder>6</showorder>
			<pages>
				<page>wcf\acp\page\ArticleListPage</page>
			</pages>
		</action>
		<action name="assignUserByClipboard">
			<actionclassname>wcf\system\clipboard\action\ModerationQueueClipboardAction</actionclassname>
			<showorder>1</showorder>
			<pages>
				<page>wcf\page\ModerationListPage</page>
			</pages>
		</action>
		<action name="enableContent">
			<actionclassname>wcf\system\clipboard\action\ModerationQueueActivationClipboardAction</actionclassname>
			<showorder>2</showorder>
			<pages>
				<page>wcf\page\ModerationListPage</page>
			</pages>
		</action>
		<action name="removeActivationContent">
			<actionclassname>wcf\system\clipboard\action\ModerationQueueActivationClipboardAction</actionclassname>
			<showorder>3</showorder>
			<pages>
				<page>wcf\page\ModerationListPage</page>
			</pages>
		</action>
		<action name="removeReport">
			<actionclassname>wcf\system\clipboard\action\ModerationQueueReportClipboardAction</actionclassname>
			<showorder>4</showorder>
			<pages>
				<page>wcf\page\ModerationListPage</page>
			</pages>
		</action>
		<action name="removeReportContent">
			<actionclassname>wcf\system\clipboard\action\ModerationQueueReportClipboardAction</actionclassname>
			<showorder>5</showorder>
			<pages>
				<page>wcf\page\ModerationListPage</page>
			</pages>
		</action>
	</import>
</data>
