=== WoltLab/WCF/XSD/cronjob.xsd
<?xml version="1.0"?>
<!-- The file "cronjobs.xsd" is used for xml-files which installs, updates or deletes searchable cronjobs. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element type -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="cronjob" type="cronjob" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- delete element type -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="cronjob" type="cronjob" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- cronjob element type -->
	<xs:complexType name="cronjob">
		 <xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="classname" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="description" type="description_element" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="startminute" type="woltlab_varchar" minOccurs="1" />
			<xs:element name="starthour" type="woltlab_varchar" minOccurs="1" />
			<xs:element name="startdom" type="woltlab_varchar" minOccurs="1" />
			<xs:element name="startmonth" type="woltlab_varchar" minOccurs="1" />
			<xs:element name="startdow" type="woltlab_varchar" minOccurs="1" />
			<xs:element name="execmultiple" type="woltlab_boolean" minOccurs="0" default="0" />
			<xs:element name="canbeedited" type="woltlab_boolean" minOccurs="0" default="1" />
			<xs:element name="canbedisabled" type="woltlab_boolean" minOccurs="0" default="1" />
			<xs:element name="isdisabled" type="woltlab_boolean" minOccurs="0" default="0" />
			<xs:element name="active" type="woltlab_boolean" minOccurs="0" default="1" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="description_element">
		<xs:simpleContent>
			<xs:extension base="woltlab_varchar">
				<xs:attribute name="language" type="woltlab_varchar" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/cronjob.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/vortex/cronjob.xsd">
	<import>
		<cronjob name="com.woltlab.wcf.refreshPackageUpdates">
			<classname>wcf\system\cronjob\GetUpdateInfoCronjob</classname>
			<description>Updates package information</description>
			<description language="de">Aktualisiert Paket-Informationen</description>
			<startminute>0</startminute>
			<starthour>2</starthour>
			<startdom>*/2</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.refreshSearchRobots">
			<classname>wcf\system\cronjob\RefreshSearchRobotsCronjob</classname>
			<description>Refreshes list of search robots</description>
			<description language="de">Aktualisiert die Liste der Suchroboter</description>
			<startminute>0</startminute>
			<starthour>3</starthour>
			<startdom>1</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.dailyCleanUp">
			<classname>wcf\system\cronjob\DailyCleanUpCronjob</classname>
			<description>Executes daily Cleanup</description>
			<description language="de">Führt tägliche Aufräumarbeiten aus</description>
			<startminute>0</startminute>
			<starthour>1</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.hourlyCleanUp">
			<classname>wcf\system\cronjob\HourlyCleanUpCronjob</classname>
			<description>Executes hourly Cleanup</description>
			<description language="de">Führt stündliche Aufräumarbeiten aus</description>
			<startminute>0</startminute>
			<starthour>*</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.sessionCleanUp">
			<classname>wcf\system\cronjob\SessionCleanUpCronjob</classname>
			<description>Deletes expired sessions</description>
			<description language="de">Löscht abgelaufene Sessions</description>
			<startminute>*/30</startminute>
			<starthour>*</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.attachmentCleanUp">
			<classname>wcf\system\cronjob\AttachmentCleanUpCronjob</classname>
			<description>Deletes orphaned attachments</description>
			<description language="de">Löscht verwaiste Dateianhänge</description>
			<startminute>0</startminute>
			<starthour>2</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.backgroundQueueCleanUp">
			<classname>wcf\system\cronjob\BackgroundQueueCleanUpCronjob</classname>
			<description>Requeues stuck queue items</description>
			<description language="de">Räumt Hintergrundaufgaben auf</description>
			<startminute>*/10</startminute>
			<starthour>*</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.lastActivityUpdate">
			<classname>wcf\system\cronjob\LastActivityCronjob</classname>
			<description>Updates last activity timestamp</description>
			<description language="de">Aktualisiert Zeitpunkt der letzten Aktivität</description>
			<startminute>*/5</startminute>
			<starthour>*</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<active>1</active>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.userQuit">
			<classname>wcf\system\cronjob\UserQuitCronjob</classname>
			<description>Deletes canceled user accounts</description>
			<description language="de">Löscht gekündigte Benutzer-Accounts</description>
			<startminute>0</startminute>
			<starthour>0</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<active>1</active>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.dailyMailNotification">
			<classname>wcf\system\cronjob\DailyMailNotificationCronjob</classname>
			<description>Sends daily mail notifications</description>
			<description language="de">Versendet tägliche E-Mail-Benachrichtigungen</description>
			<startminute>*/30</startminute>
			<starthour>*</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<active>1</active>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.moderationQueueCleanup">
			<classname>wcf\system\cronjob\ModerationQueueCronjob</classname>
			<description>Moderation queue cleanup</description>
			<description language="de">Löscht veraltete Einträge in der Moderation</description>
			<startminute>0</startminute>
			<starthour>1</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<active>1</active>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.statDailyBuilder">
			<classname>wcf\system\cronjob\StatDailyBuilderCronjob</classname>
			<description>Builds the daily statistics</description>
			<description language="de">Generiert die täglichen Statistiken</description>
			<startminute>0</startminute>
			<starthour>1</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<active>1</active>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.userGroupAssignment">
			<classname>wcf\system\cronjob\UserGroupAssignmentCronjob</classname>
			<description>Automatically assigns users to user groups</description>
			<description language="de">Ordnet Benutzer automatisch Benutzergruppen zu</description>
			<startminute>*/30</startminute>
			<starthour>*</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<active>1</active>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.userBan">
			<classname>wcf\system\cronjob\UserBanCronjob</classname>
			<description>Unbans users and enables disabled avatars and disabled signatures</description>
			<description language="de">Entsperrt gesperrte Benutzer, Avatare und Signaturen</description>
			<startminute>0</startminute>
			<starthour>1</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<active>1</active>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.articlePublication">
			<classname>wcf\system\cronjob\ArticlePublicationCronjob</classname>
			<description>Publishes delayed articles</description>
			<description language="de">Veröffentlicht Artikel</description>
			<startminute>*/5</startminute>
			<starthour>*</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.expiringPaidSubscriptionUser">
			<classname>wcf\system\cronjob\ExpiringPaidSubscriptionUserCronjob</classname>
			<description>Sends notifications about expiring paid subscriptions</description>
			<description language="de">Sendet Benachrichtigungen über ablaufende bezahlte Mitgliedschaften</description>
			<startminute>0</startminute>
			<starthour>2</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.rebuildSitemap">
			<classname>wcf\system\cronjob\RebuildSitemapCronjob</classname>
			<description>Rebuilds the sitemap</description>
			<description language="de">Aktualisiert die Sitemap</description>
			<startminute>0</startminute>
			<starthour>3</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
		
		<cronjob name="com.woltlab.wcf.assignTrophies">
			<classname>wcf\system\cronjob\AssignTrophiesCronjob</classname>
			<description>Assign trophies based on rules</description>
			<description language="de">Ordnet Trophäen aufgrund der Regeln zu</description>
			<startminute>*/5</startminute>
			<starthour>*</starthour>
			<startdom>*</startdom>
			<startmonth>*</startmonth>
			<startdow>*</startdow>
			<canbeedited>1</canbeedited>
			<canbedisabled>1</canbedisabled>
		</cronjob>
	</import>
	
	<delete>
		<!-- cronjobs with names now -->
		<cronjob>
			<classname>wcf\system\cronjob\GetUpdateInfoCronjob</classname>
		</cronjob>
		
		<cronjob>
			<classname>wcf\system\cronjob\RefreshSearchRobotsCronjob</classname>
		</cronjob>
		
		<cronjob>
			<classname>wcf\system\cronjob\DailyCleanUpCronjob</classname>
		</cronjob>
		
		<cronjob>
			<classname>wcf\system\cronjob\HourlyCleanUpCronjob</classname>
		</cronjob>
		
		<cronjob>
			<classname>wcf\system\cronjob\SessionCleanUpCronjob</classname>
		</cronjob>
		
		<cronjob>
			<classname>wcf\system\cronjob\AttachmentCleanUpCronjob</classname>
		</cronjob>
		
		<cronjob>
			<classname>wcf\system\cronjob\LastActivityCronjob</classname>
		</cronjob>
		
		<cronjob>
