=== WoltLab/WCF/XSD/dashboardBox.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install, update or delete user group options. -->
<xs:schema xmlns:xs="https://www.w3.org/2001/XMLSchema" xmlns="https://www.woltlab.com" targetNamespace="https://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />

	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<!-- import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="dashboardbox" type="dashboardbox" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- delete element type -->
	<xs:complexType name="delete">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="dashboardbox" type="dashboardbox" minOccurs="0" />
		</xs:choice>
	</xs:complexType>

	<!-- dashboardbox import element type -->
	<xs:complexType name="dashboardbox">
		<xs:complexContent>
			<xs:extension base="dashboardbox_basic">
				<xs:all>
					<xs:element name="classname" type="woltlab_varchar" minOccurs="1" />
					<xs:element name="boxtype" type="woltlab_boxtype" minOccurs="1" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="woltlab_boxtype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="sidebar" />
			<xs:enumeration value="content" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="dashboardbox_basic">
		<xs:attribute name="name" type="woltlab_varchar" />
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/dashboardBox.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/maelstrom/dashboardBox.xsd">
	<import>
		<dashboardbox name="com.woltlab.wcf.user.recentActivity">
			<classname><![CDATA[wcf\system\dashboard\box\RecentActivityDashboardBox]]></classname>
			<boxtype>content</boxtype>
		</dashboardbox>
		
		<dashboardbox name="com.woltlab.wcf.user.recentActivitySidebar">
			<classname><![CDATA[wcf\system\dashboard\box\RecentActivitySidebarDashboardBox]]></classname>
			<boxtype>sidebar</boxtype>
		</dashboardbox>
		
		<dashboardbox name="com.woltlab.wcf.user.registerButton">
			<classname><![CDATA[wcf\system\dashboard\box\RegisterButtonDashboardBox]]></classname>
			<boxtype>sidebar</boxtype>
		</dashboardbox>
		
		<dashboardbox name="com.woltlab.wcf.user.signedInAs">
			<classname><![CDATA[wcf\system\dashboard\box\SignedInAsDashboardBox]]></classname>
			<boxtype>sidebar</boxtype>
		</dashboardbox>
		
		<dashboardbox name="com.woltlab.wcf.user.statsSidebar">
			<classname><![CDATA[wcf\system\dashboard\box\StatsSidebarDashboardBox]]></classname>
			<boxtype>sidebar</boxtype>
		</dashboardbox>
		
		<dashboardbox name="com.woltlab.wcf.user.newestMembers">
			<classname><![CDATA[wcf\system\dashboard\box\NewestMembersDashboardBox]]></classname>
			<boxtype>sidebar</boxtype>
		</dashboardbox>
		
		<dashboardbox name="com.woltlab.wcf.user.mostActiveMembers">
			<classname><![CDATA[wcf\system\dashboard\box\MostActiveMembersDashboardBox]]></classname>
			<boxtype>sidebar</boxtype>
		</dashboardbox>
		
		<dashboardbox name="com.woltlab.wcf.like.mostLikedMembers">
			<classname><![CDATA[wcf\system\dashboard\box\MostLikedMembersDashboardBox]]></classname>
			<boxtype>sidebar</boxtype>
		</dashboardbox>
	</import>
</data>
