=== WoltLab/WCF/XSD/eventListener.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install, update or delete event listeners. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data node -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element type -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="eventlistener" type="eventlistener" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- delete element type -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="eventlistener" type="eventlistener" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- event listener element type -->
	<xs:complexType name="eventlistener">
		<xs:all>
			<xs:element name="eventclassname">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="80" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="eventname" type="xs:string" minOccurs="0" />
			<xs:element name="listenerclassname">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="200" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="inherit" type="woltlab_boolean" minOccurs="0" />
			<xs:element name="environment" type="woltlab_environment" minOccurs="0" />
			<xs:element name="nice" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="-128" />
						<xs:maxInclusive value="127" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="options" type="xs:string" minOccurs="0" />
			<xs:element name="permissions" type="xs:string" minOccurs="0" />
		</xs:all>
		<xs:attribute name="name" type="woltlab_varchar" use="optional" />
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/eventListener.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/vortex/eventListener.xsd">
	<import>
		<eventlistener name="sessionPageAccessLog">
			<eventclassname>wcf\page\AbstractPage</eventclassname>
			<eventname>readParameters</eventname>
			<environment>admin</environment>
			<inherit>1</inherit>
			<listenerclassname>wcf\system\event\listener\SessionAccessLogListener</listenerclassname>
		</eventlistener>
		<eventlistener name="sessionFormAccessLog">
			<eventclassname>wcf\form\AbstractForm</eventclassname>
			<eventname>readParameters</eventname>
			<environment>admin</environment>
			<inherit>1</inherit>
			<listenerclassname>wcf\system\event\listener\SessionAccessLogListener</listenerclassname>
		</eventlistener>
		<eventlistener name="sessionActionAccessLog">
			<eventclassname>wcf\action\AbstractAction</eventclassname>
			<eventname>readParameters</eventname>
			<environment>admin</environment>
			<inherit>1</inherit>
			<listenerclassname>wcf\system\event\listener\SessionAccessLogListener</listenerclassname>
		</eventlistener>
		
		<eventlistener name="articleLinkhtmlInputNodeProcessor">
			<eventclassname>wcf\system\html\input\node\HtmlInputNodeProcessor</eventclassname>
			<eventname>afterProcess</eventname>
			<listenerclassname>wcf\system\event\listener\ArticleLinkHtmlInputNodeProcessorListener</listenerclassname>
		</eventlistener>
		<eventlistener name="articleLinkhtmlInputNodeProcessorAdmin">
			<eventclassname>wcf\system\html\input\node\HtmlInputNodeProcessor</eventclassname>
			<eventname>afterProcess</eventname>
			<listenerclassname>wcf\system\event\listener\ArticleLinkHtmlInputNodeProcessorListener</listenerclassname>
			<environment>admin</environment>
		</eventlistener>
	</import>
	
	<delete>
		<!-- event listeners with names now -->
		<eventlistener>
			<eventclassname>wcf\page\AbstractPage</eventclassname>
			<eventname>readParameters</eventname>
			<environment>admin</environment>
			<inherit>1</inherit>
			<listenerclassname>wcf\system\event\listener\SessionAccessLogListener</listenerclassname>
		</eventlistener>
		<eventlistener>
			<eventclassname>wcf\form\AbstractForm</eventclassname>
			<eventname>readParameters</eventname>
			<environment>admin</environment>
			<inherit>1</inherit>
			<listenerclassname>wcf\system\event\listener\SessionAccessLogListener</listenerclassname>
		</eventlistener>
		<eventlistener>
			<eventclassname>wcf\action\AbstractAction</eventclassname>
			<eventname>readParameters</eventname>
			<environment>admin</environment>
			<inherit>1</inherit>
			<listenerclassname>wcf\system\event\listener\SessionAccessLogListener</listenerclassname>
		</eventlistener>
		<!-- /event listeners with names now -->
		
		<eventlistener>
			<eventclassname>wcf\system\bbcode\PreParser</eventclassname>
			<eventname>beforeParsing</eventname>
			<listenerclassname>wcf\system\event\listener\PreParserAtUserListener</listenerclassname>
			<environment>user</environment>
		</eventlistener>
	</delete>
</data>

=== WoltLab/WCF/com.woltlab.wcf/eventlistener.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/maelstrom/eventListener.xsd">
	<import>
		<eventlistener>
			<eventclassname>wcf\page\AbstractPage</eventclassname>
			<eventname>readParameters</eventname>
			<inherit>1</inherit>
			<listenerclassname>wcf\system\event\listener\SessionAccessLogListener</listenerclassname>
		</eventlistener>
		<eventlistener>
			<eventclassname>wcf\form\AbstractForm</eventclassname>
			<eventname>readParameters</eventname>
			<inherit>1</inherit>
			<listenerclassname>wcf\system\event\listener\SessionAccessLogListener</listenerclassname>
		</eventlistener>
		<eventlistener>
			<eventclassname>wcf\action\AbstractAction</eventclassname>
			<eventname>readParameters</eventname>
			<inherit>1</inherit>
			<listenerclassname>wcf\system\event\listener\SessionAccessLogListener</listenerclassname>
		</eventlistener>
	</import>
</data>
