=== WoltLab/WCF/XSD/objectType.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install, update or delete user group options. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="type" type="type_import" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- import element -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="type" type="type_delete" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- import element type -->
	<xs:complexType name="type_import">
		<xs:all>
			<xs:element name="name" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="definitionname" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="classname" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="category" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="categoryname" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="points" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="listclassname" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="languagevariable" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="controller" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="allowcontent" type="woltlab_boolean" minOccurs="0" />
			<xs:element name="allowsidebar" type="woltlab_boolean" minOccurs="0" />
			<xs:element name="nicevalue" type="xs:integer" minOccurs="0" />
		</xs:all>
	</xs:complexType>
	
	<!-- delete element type -->
	<xs:complexType name="type_delete">
		<xs:all>
			<xs:element name="name" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="definitionname" type="woltlab_varchar_nullable" minOccurs="0" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/objectType.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/vortex/objectType.xsd">
	<import>
		<!-- clipboard items -->
		<type>
			<name>com.woltlab.wcf.user</name>
			<definitionname>com.woltlab.wcf.clipboardItem</definitionname>
			<listclassname>wcf\data\user\UserList</listclassname>
		</type>
		<type>
			<name>com.woltlab.wcf.tag</name>
			<definitionname>com.woltlab.wcf.clipboardItem</definitionname>
			<listclassname>wcf\data\tag\TagList</listclassname>
		</type>
		<type>
			<name>com.woltlab.wcf.media</name>
			<definitionname>com.woltlab.wcf.clipboardItem</definitionname>
			<listclassname>wcf\data\media\ViewableMediaList</listclassname>
		</type>
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.clipboardItem</definitionname>
			<listclassname>wcf\data\article\ArticleList</listclassname>
		</type>
		<!-- /clipboard items -->
		
		<!-- articles -->
		<type>
			<name>com.woltlab.wcf.article.category</name>
			<definitionname>com.woltlab.wcf.category</definitionname>
			<classname>wcf\system\category\ArticleCategoryType</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article.category</name>
			<definitionname>com.woltlab.wcf.acl</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.tagging.taggableObject</definitionname>
			<classname>wcf\system\tagging\TaggableArticle</classname>
			<options>module_article</options>
		</type>
		<type>
			<name>com.woltlab.wcf.likeableArticle</name>
			<definitionname>com.woltlab.wcf.like.likeableObject</definitionname>
			<classname>wcf\data\article\LikeableArticleProvider</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.likeableArticle.recentActivityEvent</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\LikeableArticleUserActivityEvent</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.articleComment.recentActivityEvent</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\ArticleCommentUserActivityEvent</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.articleComment.response.recentActivityEvent</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\ArticleCommentResponseUserActivityEvent</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.searchableObjectType</definitionname>
			<classname>wcf\system\search\ArticleSearch</classname>
			<searchindex>wcf1_article_search_index</searchindex>
		</type>
		<type>
			<name>com.woltlab.wcf.article.content</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.label.object</definitionname>
			<classname>wcf\system\label\object\ArticleLabelObjectHandler</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article.category</name>
			<definitionname>com.woltlab.wcf.label.objectType</definitionname>
			<classname>wcf\system\label\object\type\ArticleCategoryLabelObjectTypeHandler</classname>
		</type>
		<!-- /articles -->
		
		<type>
			<name>com.woltlab.wcf.page.content</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.box.content</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.user.aboutMe</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.user.signature</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.comment</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.comment.response</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.paidSubscription</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.user.option.generic</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		
		<type>
			<name>com.woltlab.wcf.page</name>
			<definitionname>com.woltlab.wcf.searchableObjectType</definitionname>
			<classname>wcf\system\search\PageSearch</classname>
			<searchindex>wcf1_page_search_index</searchindex>
		</type>
		
		<type>
			<name>com.woltlab.wcf.bbcode.smiley</name>
			<definitionname>com.woltlab.wcf.category</definitionname>
			<classname>wcf\system\category\SmileyCategoryType</classname>
		</type>
		
		<type>
			<name>com.woltlab.wcf.user.follow</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\UserFollowUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.user</category>
		</type>
		
		<type>
			<name>com.woltlab.wcf.user.recentActivityEvent.follow</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\FollowUserActivityEvent</classname>
		</type>
		
		<type>
			<name>com.woltlab.wcf.user</name>
			<definitionname>com.woltlab.wcf.moderation.report</definitionname>
			<classname>wcf\system\moderation\queue\report\UserModerationQueueReportHandler</classname>
		</type>
		
		<!-- moderation type -->
		<type>
			<name>com.woltlab.wcf.moderation.activation</name>
			<definitionname>com.woltlab.wcf.moderation.type</definitionname>
			<classname>wcf\system\moderation\queue\ModerationQueueActivationManager</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.moderation.report</name>
			<definitionname>com.woltlab.wcf.moderation.type</definitionname>
			<classname>wcf\system\moderation\queue\ModerationQueueReportManager</classname>
		</type>
		<!-- /moderation type -->
		
		<!-- version tracker -->
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.versionTracker.objectType</definitionname>
			<classname>wcf\system\version\ArticleVersionTrackerProvider</classname>
			<tableName>wcf1_article</tableName>
			<tablePrimaryKey>articleID</tablePrimaryKey>
		</type>
		<type>
			<name>com.woltlab.wcf.box</name>
			<definitionname>com.woltlab.wcf.versionTracker.objectType</definitionname>
			<classname>wcf\system\version\BoxVersionTrackerProvider</classname>
			<tableName>wcf1_box</tableName>
			<tablePrimaryKey>boxID</tablePrimaryKey>
		</type>
		<type>
			<name>com.woltlab.wcf.page</name>
			<definitionname>com.woltlab.wcf.versionTracker.objectType</definitionname>
			<classname>wcf\system\version\PageVersionTrackerProvider</classname>
			<tableName>wcf1_page</tableName>
			<tablePrimaryKey>pageID</tablePrimaryKey>
		</type>
		<!-- /version tracker -->
		
		<!-- Visit Tracker -->
		<type>
			<name>com.woltlab.wcf.moderation.queue</name>
			<definitionname>com.woltlab.wcf.visitTracker.objectType</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.visitTracker.objectType</definitionname>
		</type>
		<!-- /Visit Tracker -->
		
		<!-- activity points -->
		<type>
			<name>com.woltlab.wcf.like.activityPointEvent.receivedLikes</name>
			<definitionname>com.woltlab.wcf.user.activityPointEvent</definitionname>
			<points>1</points>
		</type>
		<!-- /activity points -->
		
		<!-- comments -->
		<type>
			<name>com.woltlab.wcf.user.profileComment</name>
			<definitionname>com.woltlab.wcf.comment.commentableContent</definitionname>
			<classname>wcf\system\comment\manager\UserProfileCommentManager</classname>
		</type>
		
		<type>
			<name>com.woltlab.wcf.comment</name>
			<definitionname>com.woltlab.wcf.like.likeableObject</definitionname>
			<classname>wcf\data\comment\LikeableCommentProvider</classname>
		</type>
		
		<type>
			<name>com.woltlab.wcf.comment.response</name>
			<definitionname>com.woltlab.wcf.like.likeableObject</definitionname>
			<classname>wcf\data\comment\response\LikeableCommentResponseProvider</classname>
		</type>
		
		<type>
			<name>com.woltlab.wcf.user.profileComment.recentActivityEvent</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\ProfileCommentUserActivityEvent</classname>
		</type>
		
		<type>
			<name>com.woltlab.wcf.user.profileComment.response.recentActivityEvent</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\ProfileCommentResponseUserActivityEvent</classname>
		</type>
		
		<type>
			<name>com.woltlab.wcf.user.profileComment.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\UserProfileCommentUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.user</category>
		</type>
		<type>
			<name>com.woltlab.wcf.user.profileComment.response.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\UserProfileCommentResponseUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.user</category>
		</type>
		
		<type>
			<name>com.woltlab.wcf.user.profileComment.like.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\LikeUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.user</category>
		</type>
		<type>
			<name>com.woltlab.wcf.user.profileComment.response.like.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
