=== WoltLab/WCF/XSD/objectTypeDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is used for xml-files which install, update or delete page menu items. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="definition" type="definition_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- delete element -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="definition" type="definition_delete" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- imported/updated page menu item element -->
	<xs:complexType name="definition_import">
		<xs:all>
			<xs:element name="name" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="interfacename" type="woltlab_varchar_nullable" minOccurs="0" />
		</xs:all>
	</xs:complexType>
	
	<!-- imported/updated page menu item element -->
	<xs:complexType name="definition_delete">
		<xs:all>
			<xs:element name="name" type="woltlab_varchar_nullable" minOccurs="0" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/objectTypeDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/2019/objectTypeDefinition.xsd">
	<import>
		<definition>
			<name>com.woltlab.wcf.acl</name>
		</definition>
		<definition>
			<name>com.woltlab.wcf.acl.simple</name>
		</definition>
		<definition>
			<name>com.woltlab.wcf.collapsibleContent</name>
		</definition>
		<definition>
			<name>com.woltlab.wcf.clipboardItem</name>
		</definition>
		<definition>
			<name>com.woltlab.wcf.category</name>
			<interfacename>wcf\system\category\ICategoryType</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.modifiableContent</name>
			<interfacename>wcf\system\log\modification\IExtendedModificationLogHandler</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.attachment.objectType</name>
			<interfacename>wcf\system\attachment\IAttachmentObjectType</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.message.quote</name>
			<interfacename>wcf\system\message\quote\IMessageQuoteHandler</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.user.recentActivityEvent</name>
			<interfacename>wcf\system\user\activity\event\IUserActivityEvent</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.user.activityPointEvent</name>
		</definition>
		<definition>
			<name>com.woltlab.wcf.notification.objectType</name>
			<interfacename>wcf\system\user\notification\object\type\IUserNotificationObjectType</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.user.objectWatch</name>
			<interfacename>wcf\system\user\object\watch\IUserObjectWatch</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.visitTracker.objectType</name>
		</definition>
		<definition>
			<name>com.woltlab.wcf.moderation.type</name>
			<interfacename>wcf\system\moderation\queue\IModerationQueueManager</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.moderation.activation</name>
			<interfacename>wcf\system\moderation\queue\activation\IModerationQueueActivationHandler</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.moderation.report</name>
			<interfacename>wcf\system\moderation\queue\report\IModerationQueueReportHandler</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.like.likeableObject</name>
			<interfacename>wcf\data\like\ILikeObjectTypeProvider</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.edit.historySavingObject</name>
			<interfacename>wcf\system\edit\IHistorySavingObjectTypeProvider</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.versionTracker.objectType</name>
			<interfacename>wcf\system\version\IVersionTrackerProvider</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.comment.commentableContent</name>
			<interfacename>wcf\system\comment\manager\ICommentManager</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.label.object</name>
			<interfacename>wcf\system\label\object\ILabelObjectHandler</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.label.objectType</name>
			<interfacename>wcf\system\label\object\type\ILabelObjectTypeHandler</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.tagging.taggableObject</name>
			<interfacename>wcf\system\tagging\ITaggable</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.deletedContent</name>
			<interfacename>wcf\system\moderation\IDeletedContentProvider</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.searchableObjectType</name>
			<interfacename>wcf\system\search\ISearchableObjectType</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.poll</name>
			<interfacename>wcf\system\poll\IPollHandler</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.importer</name>
			<interfacename>wcf\system\importer\IImporter</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.exporter</name>
			<interfacename>wcf\system\exporter\IExporter</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.rebuildData</name>
			<interfacename>wcf\system\worker\IRebuildDataWorker</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.statDailyHandler</name>
			<interfacename>wcf\system\stat\IStatDailyHandler</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.condition.userGroupAssignment</name>
			<interfacename>wcf\system\condition\IUserCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.condition.trophy</name>
			<interfacename>wcf\system\condition\IUserCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.condition.notice</name>
			<interfacename>wcf\system\condition\IContentCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.condition.userSearch</name>
			<interfacename>wcf\system\condition\IObjectListCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.adLocation</name>
		</definition>
		<definition>
			<name>com.woltlab.wcf.condition.ad</name>
			<interfacename>wcf\system\condition\IContentCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.captcha</name>
			<interfacename>wcf\system\captcha\ICaptchaHandler</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.message.embeddedObject</name>
			<interfacename>wcf\system\message\embedded\object\IMessageEmbeddedObjectHandler</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.message</name>
		</definition>
		<definition>
			<name>com.woltlab.wcf.payment.method</name>
			<interfacename>wcf\system\payment\method\IPaymentMethod</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.payment.type</name>
			<interfacename>wcf\system\payment\type\IPaymentType</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.bulkProcessableObject</name>
			<interfacename>wcf\system\bulk\processing\IBulkProcessableObjectType</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.bulkProcessing.user.condition</name>
			<interfacename>wcf\system\condition\IObjectListCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.bulkProcessing.user.action</name>
			<interfacename>wcf\system\bulk\processing\IBulkProcessingAction</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.boxController</name>
			<interfacename>wcf\system\box\IBoxController</interfacename>
		</definition>
		<!-- box conditions -->
		<definition>
			<name>com.woltlab.wcf.box.articleList.condition</name>
			<interfacename>wcf\system\condition\IObjectListCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.box.recentActivityList.condition</name>
			<interfacename>wcf\system\condition\IObjectListCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.box.todaysBirthdays.condition</name>
			<interfacename>wcf\system\condition\IObjectCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.box.todaysFollowingBirthdays.condition</name>
			<interfacename>wcf\system\condition\IObjectCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.box.userList.condition</name>
			<interfacename>wcf\system\condition\IObjectListCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.box.userTrophyList.condition</name>
			<interfacename>wcf\system\condition\IObjectListCondition</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.box.userOnlineList.condition</name>
			<interfacename>wcf\system\condition\IObjectListCondition</interfacename>
		</definition>
		<!-- /box conditions -->
		<definition>
			<name>com.woltlab.wcf.sitemap.object</name>
			<interfacename>wcf\system\sitemap\object\ISitemapObjectObjectType</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.article.discussionProvider</name>
			<interfacename>wcf\system\article\discussion\IArticleDiscussionProvider</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.content.userContentProvider</name>
			<interfacename>wcf\system\user\content\provider\IUserContentProvider</interfacename>
		</definition>
		<definition>
			<name>com.woltlab.wcf.floodControl</name>
		</definition>
	</import>
	<delete>
		<definition name="com.woltlab.wcf.notification.notificationType"/>
	</delete>
</data>
