=== WoltLab/WCF/XSD/option.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- The file "option.xsd" is used for xml-files which installs, updates or deletes options. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- include option types -->
	<xs:include schemaLocation="optionTypes.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element type -->
	<xs:complexType name="import">
		 <xs:all>
			<xs:element name="categories" type="categories_import" minOccurs="0" />
			<xs:element name="options" type="options_import" minOccurs="0" />
		</xs:all>
	</xs:complexType>
	
	<!-- categories import element type -->
	<xs:complexType name="categories_import">
		<xs:sequence>
			<xs:element name="category" type="category_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- imported/updated category element type -->
	<xs:complexType name="category_import">
		<xs:complexContent>
			<xs:extension base="category_delete">
				<xs:all>
					<xs:element name="parent" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="showorder" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="options" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="permissions" type="woltlab_varchar_nullable" minOccurs="0" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- options import element type -->
	<xs:complexType name="options_import">
		<xs:sequence>
			<xs:element name="option" type="option_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- imported/updated element type -->
	<xs:complexType name="option_import">
		<xs:complexContent>
			<xs:extension base="option_delete">
				<xs:all>
					<xs:element name="categoryname" type="woltlab_varchar" minOccurs="1" />
					<xs:element name="optiontype" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="defaultvalue" type="xs:string" minOccurs="0" />
					<xs:element name="validationpattern" type="xs:string" minOccurs="0" />
					<xs:element name="selectoptions" type="xs:string" minOccurs="0" />
					<xs:element name="enableoptions" type="xs:string" minOccurs="0" />
					<xs:element name="hidden" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="showorder" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="options" type="xs:string" minOccurs="0" />
					<xs:element name="permissions" type="xs:string" minOccurs="0" />
					<xs:element name="supporti18n" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="suffix" type="xs:string" minOccurs="0" />
					<xs:element name="minvalue" type="xs:int" minOccurs="0" />
					<xs:element name="maxvalue" type="xs:int" minOccurs="0" />
					<xs:element name="minlength" type="xs:int" minOccurs="0" />
					<xs:element name="maxlength" type="xs:int" minOccurs="0" />
					<xs:element name="allowemptyvalue" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="disableAutocomplete" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="issortable" type="woltlab_boolean" minOccurs="0" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/option.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/6.0/option.xsd">
	<import>
		<categories>
			<!-- modules -->
			<category name="module">
				<showorder>1</showorder>
			</category>
			<category name="module.system">
				<parent>module</parent>
			</category>
			<category name="module.user">
				<parent>module</parent>
			</category>
			<category name="module.customization">
				<parent>module</parent>
			</category>
			<category name="module.content">
				<parent>module</parent>
			</category>
			<category name="module.community">
				<parent>module</parent>
			</category>
			<category name="module.development">
				<parent>module</parent>
			</category>
			<!-- /modules -->
			<!-- general -->
			<category name="general">
				<showorder>2</showorder>
			</category>
			<category name="general.page">
				<parent>general</parent>
				<showorder>1</showorder>
			</category>
			<category name="general.page.seo">
				<parent>general.page</parent>
			</category>
			<category name="general.page.sitemap">
				<parent>general.page</parent>
			</category>
			<category name="general.offline">
				<parent>general</parent>
				<showorder>2</showorder>
			</category>
			<category name="general.system">
				<parent>general</parent>
				<showorder>3</showorder>
			</category>
			<category name="general.system.ipAddress">
				<parent>general.system</parent>
			</category>
			<category name="general.system.error">
				<parent>general.system</parent>
			</category>
			<category name="general.system.cookie">
				<parent>general.system</parent>
			</category>
			<category name="general.system.http">
				<parent>general.system</parent>
			</category>
			<category name="general.system.packageServer">
				<parent>general.system</parent>
			</category>
			<category name="general.system.proxy">
				<parent>general.system</parent>
			</category>
			<category name="general.system.image">
				<parent>general.system</parent>
			</category>
			<category name="general.system.search">
				<parent>general.system</parent>
			</category>
			<category name="general.system.date">
				<parent>general.system</parent>
			</category>
			<category name="general.system.googleMaps">
				<parent>general.system</parent>
			</category>
			<category name="general.mail">
				<parent>general</parent>
				<showorder>4</showorder>
			</category>
			<category name="general.mail.general">
				<parent>general.mail</parent>
			</category>
			<category name="general.mail.send">
				<parent>general.mail</parent>
			</category>
			<category name="general.cache">
				<parent>general</parent>
				<showorder>5</showorder>
			</category>
			<category name="general.cache.general">
				<parent>general.cache</parent>
			</category>
			<category name="general.cache.redis">
				<parent>general.cache</parent>
			</category>
			<category name="general.payment">
				<parent>general</parent>
				<showorder>6</showorder>
			</category>
			<category name="general.payment.paidSubscription">
				<parent>general.payment</parent>
			</category>
			<!-- /general -->
			<!-- user -->
			<category name="user">
				<showorder>3</showorder>
			</category>
			<category name="user.general">
				<parent>user</parent>
			</category>
			<category name="user.profile">
				<parent>user</parent>
			</category>
			<category name="user.avatar">
				<parent>user.profile</parent>
			</category>
			<category name="user.signature">
				<parent>user.profile</parent>
			</category>
			<category name="user.title">
				<parent>user.profile</parent>
			</category>
			<category name="user.cleanup">
				<parent>user.profile</parent>
			</category>
			<category name="user.list">
				<parent>user</parent>
			</category>
			<category name="user.list.members">
				<parent>user.list</parent>
			</category>
			<category name="user.list.online">
				<parent>user.list</parent>
			</category>
			<category name="user.register">
				<parent>user</parent>
			</category>
			<category name="user.3rdPartyAuth">
				<parent>user.register</parent>
			</category>
			<category name="user.password">
				<parent>user.register</parent>
			</category>
			<category name="user.ban">
				<parent>user.register</parent>
			</category>
			<!-- /user -->
			<!-- security -->
			<category name="security">
				<showorder>4</showorder>
			</category>
			<category name="security.general">
				<parent>security</parent>
			</category>
			<category name="security.general.session">
				<parent>security.general</parent>
			</category>
			<category name="security.general.authentication">
				<parent>security.general</parent>
			</category>
			<category name="security.general.secrets">
				<parent>security.general</parent>
				<showorder>15</showorder>
			</category>
			<category name="security.blacklist">
				<parent>security</parent>
			</category>
			<category name="security.blacklist.sfs">
				<parent>security.blacklist</parent>
				<showorder>1</showorder>
			</category>
			<category name="security.blacklist.custom">
				<parent>security.blacklist</parent>
				<showorder>2</showorder>
			</category>
			<category name="security.antispam">
				<parent>security</parent>
			</category>
			<category name="security.antispam.captcha">
				<parent>security.antispam</parent>
			</category>
			<category name="security.antispam.recaptcha">
				<parent>security.antispam</parent>
			</category>
			<category name="security.censorship">
				<parent>security</parent>
			</category>
			<category name="message.censorship">
				<parent>security.censorship</parent>
			</category>
			<!-- /security -->
			<!-- message -->
			<category name="message">
				<showorder>5</showorder>
			</category>
			<category name="message.general">
				<parent>message</parent>
			</category>
			<category name="message.general.share">
				<parent>message.general</parent>
			</category>
			<category name="message.general.likes">
				<parent>message.general</parent>
			</category>
			<category name="message.general.poll">
				<parent>message.general</parent>
				<options>module_poll</options>
			</category>
			<category name="message.general.edit">
				<parent>message.general</parent>
			</category>
			<category name="message.general.image">
				<parent>message.general</parent>
			</category>
			<category name="message.general.imageProxy">
				<parent>message.general</parent>
			</category>
			<category name="message.general.unfurl">
				<parent>message.general</parent>
			</category>
			<category name="message.general.formatting">
				<parent>message.general</parent>
			</category>
			<category name="message.attachment">
				<parent>message</parent>
			</category>
			<category name="message.attachment.autoscale">
				<parent>message.attachment</parent>
			</category>
			<category name="message.sidebar">
				<parent>message</parent>
			</category>
			<category name="message.search">
				<parent>message</parent>
			</category>
			<category name="message.contactForm">
				<parent>message</parent>
			</category>
			<!-- /message -->
			<category name="dashboard"/>
			<category name="dashboard.content">
				<parent>dashboard</parent>
			</category>
			<category name="dashboard.sidebar">
				<parent>dashboard</parent>
			</category>
			<!-- cms -->
			<category name="cms"/>
			<category name="cms.media">
				<parent>cms</parent>
			</category>
			<category name="cms.media.thumbnail">
				<parent>cms.media</parent>
			</category>
			<category name="cms.article">
				<parent>cms</parent>
			</category>
		</categories>
		<options>
			<option name="last_update_time">
				<categoryname>general</categoryname>
				<optiontype>integer</optiontype>
				<defaultvalue>0</defaultvalue>
				<hidden>1</hidden>
			</option>
			<!-- value will automatically be replaced during WCFSetup -->
			<option name="wcf_uuid">
				<categoryname>general</categoryname>
				<optiontype>text</optiontype>
				<defaultvalue>bd096261-15f4-5dc1-9767-01ce08d7c80b</defaultvalue>
				<hidden>1</hidden>
			</option>
			<option name="woltlab_branding">
				<categoryname>general</categoryname>
				<optiontype>integer</optiontype>
				<defaultvalue>1</defaultvalue>
				<hidden>1</hidden>
			</option>
			<option name="first_time_setup_state">
				<categoryname>general</categoryname>
				<optiontype>integer</optiontype>
				<defaultvalue>0</defaultvalue>
				<hidden>1</hidden>
			</option>
			<option name="service_worker_public_key">
				<categoryname>hidden</categoryname>
				<optiontype>text</optiontype>
				<defaultvalue></defaultvalue>
				<hidden>1</hidden>
			</option>
			<option name="service_worker_private_key">
				<categoryname>hidden</categoryname>
				<optiontype>text</optiontype>
				<defaultvalue></defaultvalue>
				<hidden>1</hidden>
			</option>
			<option name="visitor_use_tiny_build">
				<categoryname>module.system</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
			</option>
			<option name="module_article">
				<categoryname>module.content</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>1</defaultvalue>
			</option>
			<option name="module_smiley">
				<categoryname>module.customization</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>1</defaultvalue>
			</option>
			<option name="module_users_online">
				<categoryname>module.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>1</defaultvalue>
			</option>
			<option name="module_user_rank">
				<categoryname>module.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>1</defaultvalue>
			</option>
			<option name="module_user_signature">
				<categoryname>module.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>1</defaultvalue>
			</option>
			<option name="module_members_list">
				<categoryname>module.user</categoryname>
				<optiontype>boolean</optiontype>
