=== WoltLab/WCF/XSD/packageInstallationPlugin.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- This file is used for xml files which install or update package installation plugins. -->
<xs:schema id="data" targetNamespace="http://www.woltlab.com" xmlns="http://www.woltlab.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
	<xs:element name="data">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="import">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="pip" nillable="true" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="name" form="unqualified" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/packageInstallationPlugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/maelstrom/packageInstallationPlugin.xsd">
	<import>
		<pip name="acpMenu">wcf\system\package\plugin\ACPMenuPackageInstallationPlugin</pip>
		<pip name="acpTemplate">wcf\system\package\plugin\ACPTemplatePackageInstallationPlugin</pip>
		<pip name="clipboardAction">wcf\system\package\plugin\ClipboardActionPackageInstallationPlugin</pip>
		<pip name="coreObject">wcf\system\package\plugin\CoreObjectPackageInstallationPlugin</pip>
		<pip name="cronjob">wcf\system\package\plugin\CronjobPackageInstallationPlugin</pip>
		<pip name="eventListener">wcf\system\package\plugin\EventListenerPackageInstallationPlugin</pip>
		<pip name="file">wcf\system\package\plugin\FilePackageInstallationPlugin</pip>
		<pip name="language">wcf\system\package\plugin\LanguagePackageInstallationPlugin</pip>
		<pip name="objectType">wcf\system\package\plugin\ObjectTypePackageInstallationPlugin</pip>
		<pip name="objectTypeDefinition">wcf\system\package\plugin\ObjectTypeDefinitionPackageInstallationPlugin</pip>
		<pip name="option">wcf\system\package\plugin\OptionPackageInstallationPlugin</pip>
		<pip name="pageMenu">wcf\system\package\plugin\PageMenuPackageInstallationPlugin</pip>
		<pip name="route">wcf\system\package\plugin\RoutePackageInstallationPlugin</pip>
		<pip name="script">wcf\system\package\plugin\ScriptPackageInstallationPlugin</pip>
		<pip name="sql">wcf\system\package\plugin\SQLPackageInstallationPlugin</pip>
		<pip name="templateListener">wcf\system\package\plugin\TemplateListenerPackageInstallationPlugin</pip>
		<pip name="template">wcf\system\package\plugin\TemplatePackageInstallationPlugin</pip>
		<pip name="userGroupOption">wcf\system\package\plugin\UserGroupOptionPackageInstallationPlugin</pip>
		<pip name="userOption">wcf\system\package\plugin\UserOptionPackageInstallationPlugin</pip>
	</import>
</data>
