=== WoltLab/WCF/XSD/styleattributes.xsd
<?xml version="1.0"?>
<!-- The file "styleattributes.xsd" is used for xml-files which installs, updates or deletes style attributes.  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- Represents the data-node. -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- Represents the import-node. -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="attribute" type="styleattribute" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- Represents the delete-node. -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="attribute" type="styleattribute" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- Represents a styleattribute, which will be installed, updated or deleted. -->
	<xs:complexType name="styleattribute">
		<xs:all>
			<xs:element name="selector" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="200" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="name" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="50" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="value" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="50" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:all>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/styleattributes.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/maelstrom/styleattributes.xsd">
	<import>
		<attribute>
			<selector><![CDATA[]]></selector>
			<name><![CDATA[]]></name>
			<value><![CDATA[user.additional.style.input1.use]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[]]></selector>
			<name><![CDATA[]]></name>
			<value><![CDATA[user.additional.style.input2.use]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#header]]></selector>
			<name><![CDATA[border-color]]></name>
			<value><![CDATA[container.border.outer.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#header]]></selector>
			<name><![CDATA[background-color]]></name>
			<value><![CDATA[page.header.background.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#header]]></selector>
			<name><![CDATA[background-image]]></name>
			<value><![CDATA[page.header.background.image]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#header]]></selector>
			<name><![CDATA[background-position]]></name>
			<value><![CDATA[page.header.background.image.alignment]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#header]]></selector>
			<name><![CDATA[background-repeat]]></name>
			<value><![CDATA[page.header.background.image.repeat]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo]]></selector>
			<name><![CDATA[border-color]]></name>
			<value><![CDATA[container.border.inner.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo]]></selector>
			<name><![CDATA[border-bottom-width]]></name>
			<value><![CDATA[menu.main.bar.divider.show]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo]]></selector>
			<name><![CDATA[height]]></name>
			<value><![CDATA[page.header.height]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo .pageLogo]]></selector>
			<name><![CDATA[text-align]]></name>
			<value><![CDATA[page.logo.image.alignment]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo .pageLogo img]]></selector>
			<name><![CDATA[margin-left]]></name>
			<value><![CDATA[page.logo.image.padding.left]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo .pageLogo img]]></selector>
			<name><![CDATA[margin-right]]></name>
			<value><![CDATA[page.logo.image.padding.right]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo .pageLogo img]]></selector>
			<name><![CDATA[margin-top]]></name>
			<value><![CDATA[page.logo.image.padding.top]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1]]></selector>
			<name><![CDATA[font-family]]></name>
			<value><![CDATA[global.title.font]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1]]></selector>
			<name><![CDATA[text-align]]></name>
			<value><![CDATA[global.title.font.alignment]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1]]></selector>
			<name><![CDATA[color]]></name>
			<value><![CDATA[global.title.font.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1]]></selector>
			<name><![CDATA[font-size]]></name>
			<value><![CDATA[global.title.font.size]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1]]></selector>
			<name><![CDATA[font-style]]></name>
			<value><![CDATA[global.title.font.style]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1]]></selector>
			<name><![CDATA[font-weight]]></name>
			<value><![CDATA[global.title.font.weight]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1]]></selector>
			<name><![CDATA[]]></name>
			<value><![CDATA[global.title.hide]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1 a]]></selector>
			<name><![CDATA[color]]></name>
			<value><![CDATA[global.title.font.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1 a]]></selector>
			<name><![CDATA[padding-left]]></name>
			<value><![CDATA[global.title.font.padding.left]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1 a]]></selector>
			<name><![CDATA[padding-right]]></name>
			<value><![CDATA[global.title.font.padding.right]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#logo h1 a]]></selector>
			<name><![CDATA[padding-top]]></name>
			<value><![CDATA[global.title.font.padding.top]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#userPanel]]></selector>
			<name><![CDATA[]]></name>
			<value><![CDATA[page.alignment.margin]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#header]]></selector>
			<name><![CDATA[]]></name>
			<value><![CDATA[page.alignment.margin]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#footer]]></selector>
			<name><![CDATA[]]></name>
			<value><![CDATA[page.alignment.margin]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#main]]></selector>
			<name><![CDATA[]]></name>
			<value><![CDATA[page.alignment.margin]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#userPanel]]></selector>
			<name><![CDATA[width]]></name>
			<value><![CDATA[page.width]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#header]]></selector>
			<name><![CDATA[width]]></name>
			<value><![CDATA[page.width]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#footer]]></selector>
			<name><![CDATA[width]]></name>
			<value><![CDATA[page.width]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.footerOptions li]]></selector>
			<name><![CDATA[border-color]]></name>
			<value><![CDATA[container.border.outer.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.footerOptions li.extraButton]]></selector>
			<name><![CDATA[border-color]]></name>
			<value><![CDATA[buttons.small.border.outer.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.footerMenu li]]></selector>
			<name><![CDATA[border-color]]></name>
			<value><![CDATA[container.border.outer.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#main]]></selector>
			<name><![CDATA[width]]></name>
			<value><![CDATA[page.width]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#userPanel]]></selector>
			<name><![CDATA[max-width]]></name>
			<value><![CDATA[page.width.max]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#header]]></selector>
			<name><![CDATA[max-width]]></name>
			<value><![CDATA[page.width.max]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#footer]]></selector>
			<name><![CDATA[max-width]]></name>
			<value><![CDATA[page.width.max]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#main]]></selector>
			<name><![CDATA[max-width]]></name>
			<value><![CDATA[page.width.max]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#userPanel]]></selector>
			<name><![CDATA[min-width]]></name>
			<value><![CDATA[page.width.min]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#header]]></selector>
			<name><![CDATA[min-width]]></name>
			<value><![CDATA[page.width.min]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#footer]]></selector>
			<name><![CDATA[min-width]]></name>
			<value><![CDATA[page.width.min]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#main]]></selector>
			<name><![CDATA[min-width]]></name>
			<value><![CDATA[page.width.min]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[#footer]]></selector>
			<name><![CDATA[border-color]]></name>
			<value><![CDATA[container.border.outer.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[body]]></selector>
			<name><![CDATA[font-size]]></name>
			<value><![CDATA[page.font.size]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.columnContainer]]></selector>
			<name><![CDATA[border-color]]></name>
			<value><![CDATA[container.border.inner.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[* a.externalURL]]></selector>
			<name><![CDATA[color]]></name>
			<value><![CDATA[page.link.external.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[* a.externalURL:hover]]></selector>
			<name><![CDATA[color]]></name>
			<value><![CDATA[page.link.external.color.hover]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.activeContainer]]></selector>
			<name><![CDATA[background-color]]></name>
			<value><![CDATA[selection.background.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.activeContainer]]></selector>
			<name><![CDATA[background-image]]></name>
			<value><![CDATA[selection.background.image]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.activeContainer]]></selector>
			<name><![CDATA[border-color]]></name>
			<value><![CDATA[selection.border.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.activeContainer]]></selector>
			<name><![CDATA[border-style]]></name>
			<value><![CDATA[selection.border.style]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.activeContainer]]></selector>
			<name><![CDATA[border-width]]></name>
			<value><![CDATA[selection.border.width]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.activeContainer]]></selector>
			<name><![CDATA[color]]></name>
			<value><![CDATA[selection.font.color]]></value>
		</attribute>
		<attribute>
			<selector><![CDATA[.activeContainer .light]]></selector>
			<name><![CDATA[color]]></name>
			<value><![CDATA[selection.font.2nd.color]]></value>
		</attribute>
		<attribute>
