=== WoltLab/WCF/XSD/templateListener.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is used for xml-files which install, update or delete templatelisteners. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="templatelistener" type="templatelistener_import" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- delete element -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="templatelistener" type="templatelistener_delete" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- deleted templatelisteners -->
	<xs:complexType name="templatelistener_delete">
		<xs:attribute name="name" type="woltlab_varchar" use="required" />
	</xs:complexType>
	
	<!-- imported/updated templatelisteners -->
	<xs:complexType name="templatelistener_import">
		<xs:complexContent>
			<xs:extension base="templatelistener_delete">
				<xs:all>
					<xs:element name="environment" type="woltlab_environment" minOccurs="0" />
					<xs:element name="templatename" type="xs:string" minOccurs="0" />
					<xs:element name="eventname" type="xs:string" minOccurs="0" />
					<xs:element name="templatecode" type="xs:string" minOccurs="0" />
					<xs:element name="nice" minOccurs="0">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="-128" />
								<xs:maxInclusive value="127" />
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/templateListener.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/vortex/templateListener.xsd">
	<import>
		<templatelistener name="articleSortField">
			<environment>admin</environment>
			<templatename>categoryAdd</templatename>
			<eventname>dataFields</eventname>
			<templatecode><![CDATA[{include file='__articleSortField'}]]></templatecode>
		</templatelistener>
	</import>
	<delete>
		<templatelistener name="articleShowOrder">
			<environment>admin</environment>
			<templatename>categoryAdd</templatename>
			<eventname>dataFields</eventname>
		</templatelistener>
	</delete>
</data>
