=== WoltLab/WCF/XSD/userOption.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install, update or delete user options. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- include option types -->
	<xs:include schemaLocation="optionTypes.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		 <xs:all>
			<xs:element name="categories" type="categories_import" minOccurs="0" />
			<xs:element name="options" type="options_import" minOccurs="0" />
		</xs:all>
	</xs:complexType>
	
	<!-- categories import element type -->
	<xs:complexType name="categories_import">
		<xs:sequence>
			<xs:element name="category" type="category_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- imported/updated category element type -->
	<xs:complexType name="category_import">
		<xs:complexContent>
			<xs:extension base="category_delete">
				<xs:all>
					<xs:element name="icon" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="menuicon" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="parent" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="showorder" type="xs:unsignedInt" minOccurs="0" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- options import element type -->
	<xs:complexType name="options_import">
		<xs:sequence>
			<xs:element name="option" type="option_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- imported/updated element type -->
	<xs:complexType name="option_import">
		<xs:complexContent>
			<xs:extension base="option_delete">
				<xs:all>
					<xs:element name="categoryname" type="woltlab_varchar" minOccurs="1" />
					<xs:element name="optiontype" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="defaultvalue" type="xs:string" minOccurs="0" />
					<xs:element name="validationpattern" type="xs:string" minOccurs="0" />
					<xs:element name="outputclass" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="selectoptions" type="xs:string" minOccurs="0" />
					<xs:element name="enableoptions" type="xs:string" minOccurs="0" />
					<xs:element name="required" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="editable" minOccurs="0" >
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="0" />
								<xs:maxInclusive value="4" />
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="visible" minOccurs="0">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="0" />
								<xs:maxInclusive value="4" />
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="searchable" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="deactivated" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="showorder" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="options" type="xs:string" minOccurs="0" />
					<xs:element name="permissions" type="xs:string" minOccurs="0" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/userOption.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/2019/userOption.xsd">
	<import>
		<categories>
			<category name="profile">
				<showorder>1</showorder>
			</category>
			<!-- profile -->
			<category name="profile.aboutMe">
				<parent>profile</parent>
			</category>
			<category name="profile.personal">
				<parent>profile</parent>
			</category>
			<category name="profile.contact">
				<parent>profile</parent>
			</category>
			<!-- /profile -->
			<category name="settings">
				<showorder>2</showorder>
			</category>
			<!-- settings -->
			<category name="settings.general">
				<parent>settings</parent>
				<showorder>1</showorder>
			</category>
			<category name="settings.general.appearance">
				<parent>settings.general</parent>
				<showorder>1</showorder>
			</category>
			<category name="settings.general.interface">
				<parent>settings.general</parent>
				<showorder>2</showorder>
			</category>
			<category name="settings.general.date">
				<parent>settings.general</parent>
				<showorder>3</showorder>
			</category>
			<category name="settings.privacy">
				<parent>settings</parent>
				<showorder>2</showorder>
			</category>
			<category name="settings.privacy.content">
				<parent>settings.privacy</parent>
			</category>
			<category name="settings.privacy.messaging">
				<parent>settings.privacy</parent>
			</category>
		</categories>
		<options>
			<!-- profile -->
			<option name="aboutMe">
				<categoryname>profile.aboutMe</categoryname>
				<optiontype>aboutMe</optiontype>
				<outputclass>wcf\system\option\user\MessageUserOptionOutput</outputclass>
				<visible>15</visible>
				<editable>3</editable>
				<messageObjectType>com.woltlab.wcf.user.aboutMe</messageObjectType>
			</option>
			<option name="birthday">
				<categoryname>profile.personal</categoryname>
				<optiontype>birthday</optiontype>
				<outputclass>wcf\system\option\user\BirthdayUserOptionOutput</outputclass>
				<searchable>1</searchable>
				<visible>15</visible>
				<editable>3</editable>
			</option>
			<option name="birthdayShowYear">
				<categoryname>profile.personal</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>1</defaultvalue>
				<editable>3</editable>
			</option>
			<option name="gender">
				<categoryname>profile.personal</categoryname>
				<optiontype>select</optiontype>
				<defaultvalue>0</defaultvalue>
				<selectoptions>0:wcf.global.noDeclaration
1:wcf.user.gender.male
2:wcf.user.gender.female
3:wcf.user.gender.other</selectoptions>
				<outputclass>wcf\system\option\user\SelectOptionsUserOptionOutput</outputclass>
				<searchable>1</searchable>
				<visible>15</visible>
				<editable>3</editable>
			</option>
			<option name="location">
				<categoryname>profile.personal</categoryname>
				<optiontype>text</optiontype>
				<searchable>1</searchable>
				<visible>15</visible>
				<editable>3</editable>
			</option>
			<option name="occupation">
				<categoryname>profile.personal</categoryname>
				<optiontype>text</optiontype>
				<searchable>1</searchable>
				<visible>15</visible>
				<editable>3</editable>
			</option>
			<option name="hobbies">
				<categoryname>profile.personal</categoryname>
				<optiontype>text</optiontype>
				<searchable>1</searchable>
				<visible>15</visible>
				<editable>3</editable>
			</option>
			<option name="adminComment">
				<categoryname>profile.personal</categoryname>
				<optiontype>textarea</optiontype>
				<outputclass>wcf\system\option\user\NewlineToBreakUserOptionOutput</outputclass>
				<visible>2</visible>
				<editable>2</editable>
			</option>
			<option name="homepage">
				<categoryname>profile.contact</categoryname>
				<optiontype>URL</optiontype>
				<validationpattern>^$|^https?://</validationpattern>
				<outputclass>wcf\system\option\user\URLUserOptionOutput</outputclass>
				<searchable>1</searchable>
				<visible>15</visible>
				<editable>3</editable>
			</option>
			<option name="skype">
				<categoryname>profile.contact</categoryname>
				<optiontype>text</optiontype>
				<searchable>1</searchable>
				<visible>15</visible>
				<editable>3</editable>
				<isdisabled>1</isdisabled>
			</option>
			<option name="facebook">
				<categoryname>profile.contact</categoryname>
				<optiontype>text</optiontype>
				<validationpattern>^$|^[A-Za-z\d.]{5,}$</validationpattern>
				<outputclass>wcf\system\option\user\FacebookUserOptionOutput</outputclass>
				<searchable>1</searchable>
				<visible>15</visible>
				<editable>3</editable>
				<contentpattern>^https?://www.facebook.com/([A-Za-z\d.]{5,})$</contentpattern>
			</option>
			<option name="twitter">
				<categoryname>profile.contact</categoryname>
				<optiontype>text</optiontype>
				<validationpattern>^$|^[A-Za-z0-9_]+$</validationpattern>
				<outputclass>wcf\system\option\user\TwitterUserOptionOutput</outputclass>
				<searchable>1</searchable>
				<visible>15</visible>
				<editable>3</editable>
				<contentpattern>^https?://twitter.com/([A-Za-z0-9_]+)$</contentpattern>
			</option>
			<!-- /profile -->
			<!-- settings -->
			<option name="recentActivitiesFilterByFollowing">
				<categoryname>hidden</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>1</defaultvalue>
			</option>
			<option name="timezone">
				<categoryname>settings.general.date</categoryname>
				<optiontype>timezone</optiontype>
				<editable>3</editable>
			</option>
			<option name="showSignature">
				<categoryname>settings.general.appearance</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>1</defaultvalue>
				<options>module_user_signature</options>
				<editable>3</editable>
			</option>
			<option name="editorPastePreserveFormatting">
				<categoryname>settings.general.interface</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>1</defaultvalue>
				<editable>3</editable>
			</option>
			<!-- settings.privacy.content -->
			<option name="canViewOnlineStatus">
				<categoryname>settings.privacy.content</categoryname>
				<optiontype>select</optiontype>
				<defaultvalue>0</defaultvalue>
				<selectoptions>0:wcf.user.access.everyone
1:wcf.user.access.registered
2:wcf.user.access.following
3:wcf.user.access.nobody</selectoptions>
				<editable>3</editable>
				<permissions>user.profile.canHideOnlineStatus</permissions>
			</option>
			<option name="canViewProfile">
				<categoryname>settings.privacy.content</categoryname>
				<optiontype>select</optiontype>
				<defaultvalue>0</defaultvalue>
				<selectoptions>0:wcf.user.access.everyone
1:wcf.user.access.registered
2:wcf.user.access.following
3:wcf.user.access.nobody</selectoptions>
				<editable>3</editable>
			</option>
			<option name="canViewTrophies">
				<categoryname>settings.privacy.content</categoryname>
				<optiontype>select</optiontype>
				<defaultvalue>0</defaultvalue>
				<options>module_trophy</options>
				<permissions>user.profile.trophy.canSeeTrophies</permissions>
				<selectoptions>0:wcf.user.access.everyone
1:wcf.user.access.registered
2:wcf.user.access.following
3:wcf.user.access.nobody</selectoptions>
				<editable>3</editable>
			</option>
			<option name="enableEmbeddedMedia">
				<categoryname>settings.privacy.content</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<editable>3</editable>
				<options>message_enable_user_consent</options>
			</option>
			<!-- settings.privacy.messaging -->
			<option name="canViewEmailAddress">
				<categoryname>settings.privacy.messaging</categoryname>
				<optiontype>select</optiontype>
				<defaultvalue>3</defaultvalue>
				<selectoptions>0:wcf.user.access.everyone
1:wcf.user.access.registered
2:wcf.user.access.following
3:wcf.user.access.nobody</selectoptions>
				<editable>3</editable>
			</option>
			<option name="adminCanMail">
				<categoryname>settings.privacy.messaging</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>1</defaultvalue>
				<editable>3</editable>
			</option>
			<!-- /settings -->
			<option name="canWriteProfileComments">
				<categoryname>settings.privacy.messaging</categoryname>
				<optiontype>select</optiontype>
				<defaultvalue>1</defaultvalue>
				<selectoptions>0:wcf.user.access.everyone
1:wcf.user.access.registered
2:wcf.user.access.following
3:wcf.user.access.nobody</selectoptions>
				<options>module_user_profile_wall</options>
				<editable>3</editable>
			</option>
		</options>
	</import>
	<delete>
		<option name="canMail" />
	</delete>
</data>
