=== WoltLab/WCF/XSD/userGroupOption.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install, update or delete user group options. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	 <!-- include option types -->
	<xs:include schemaLocation="optionTypes.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		 <xs:all>
			<xs:element name="categories" type="categories_import" minOccurs="0" />
			<xs:element name="options" type="options_import" minOccurs="0" />
		</xs:all>
	</xs:complexType>
	
	<!-- categories import element type -->
	<xs:complexType name="categories_import">
		<xs:sequence>
			<xs:element name="category" type="category_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- imported/updated category element type -->
	<xs:complexType name="category_import">
		<xs:complexContent>
			<xs:extension base="category_delete">
				<xs:all>
					<xs:element name="parent" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="showorder" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="options" type="woltlab_varchar_nullable" minOccurs="0" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- options import element type -->
	<xs:complexType name="options_import">
		<xs:sequence>
			<xs:element name="option" type="option_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- imported/updated element type -->
	<xs:complexType name="option_import">
		<xs:complexContent>
			<xs:extension base="option_delete">
				<xs:all>
					<xs:element name="categoryname" type="woltlab_varchar" minOccurs="1" />
					<xs:element name="optiontype" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="defaultvalue" type="xs:string" minOccurs="0" />
					<xs:element name="userdefaultvalue" type="xs:string" minOccurs="0" />
					<xs:element name="moddefaultvalue" type="xs:string" minOccurs="0" />
					<xs:element name="validationpattern" type="xs:string" minOccurs="0" />
					<xs:element name="enableoptions" type="xs:string" minOccurs="0" />
					<xs:element name="showorder" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="options" type="xs:string" minOccurs="0" />
					<xs:element name="permissions" type="xs:string" minOccurs="0" />
					<xs:element name="admindefaultvalue" type="xs:string" minOccurs="0" />
					<xs:element name="usersonly" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="wildcard" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="minvalue" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="maxvalue" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="excludedInTinyBuild" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="suffix" type="woltlab_varchar" minOccurs="0" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/userGroupOption.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/maelstrom/userGroupOption.xsd">
	<import>
		<categories>
			<category name="user"></category>
			<category name="user.profile">
				<parent>user</parent>
			</category>
			<category name="user.profileComment">
				<parent>user.profile</parent>
			</category>
			<category name="user.signature">
				<parent>user.profile</parent>
			</category>
			<category name="user.profile.avatar">
				<parent>user.profile</parent>
			</category>
			
			<category name="user.message">
				<parent>user</parent>
			</category>
			<category name="user.like">
				<parent>user.message</parent>
			</category>
			<category name="user.message.attachment">
				<parent>user.message</parent>
			</category>
			
			<category name="mod"></category>
			<category name="mod.general">
				<parent>mod</parent>
			</category>
			<category name="mod.profileComment">
				<parent>mod.general</parent>
			</category>
			
			<category name="admin"></category>
			<category name="admin.general">
				<parent>admin</parent>
			</category>
			<category name="admin.system">
				<parent>admin</parent>
			</category>
			<category name="admin.system.package">
				<parent>admin.system</parent>
			</category>
			<category name="admin.maintenance">
				<parent>admin.system</parent>
			</category>
			<category name="admin.user">
				<parent>admin</parent>
			</category>
			<category name="admin.user.user">
				<parent>admin.user</parent>
			</category>
			<category name="admin.user.group">
				<parent>admin.user</parent>
			</category>
			<category name="admin.user.option">
				<parent>admin.user</parent>
			</category>
			<category name="admin.user.rank">
				<parent>admin.user</parent>
			</category>
			
			<category name="admin.display">
				<parent>admin</parent>
			</category>
			<category name="admin.style">
				<parent>admin.display</parent>
			</category>
			<category name="admin.display.pageMenu">
				<parent>admin.display</parent>
			</category>
			<category name="admin.template">
				<parent>admin.display</parent>
			</category>
			
			<category name="admin.content">
				<parent>admin</parent>
			</category>
			<category name="admin.attachment">
				<parent>admin.content</parent>
			</category>
			<category name="admin.content.bbcode">
				<parent>admin.content</parent>
			</category>
			<category name="admin.content.smiley">
				<parent>admin.content</parent>
			</category>
			<category name="admin.content.dashboard">
				<parent>admin.content</parent>
			</category>
			<category name="admin.content.label">
				<parent>admin.content</parent>
			</category>
			<category name="admin.content.tag">
				<parent>admin.content</parent>
			</category>
			
			<category name="admin.community">
				<parent>admin</parent>
			</category>
			<category name="admin.language">
				<parent>admin.display</parent>
			</category>
		</categories>
		
		<options>
			<option name="admin.general.canViewPrivateUserOptions">
				<categoryname>admin.general</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.general.canViewPageDuringOfflineMode">
				<categoryname>admin.general</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.system.canEditOption">
				<categoryname>admin.system</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.system.canViewLog">
				<categoryname>admin.system</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.system.canManageApplication">
				<categoryname>admin.system</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.system.canImportData">
				<categoryname>admin.system</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.system.canRebuildData">
				<categoryname>admin.system</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.system.canManageCronjob">
				<categoryname>admin.system</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.system.package.canUpdatePackage">
				<categoryname>admin.system.package</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.system.package.canUninstallPackage">
				<categoryname>admin.system.package</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.system.package.canEditServer">
				<categoryname>admin.system.package</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.accessibleGroups">
				<categoryname>admin.user.group</categoryname>
				<optiontype>userGroups</optiontype>
				<defaultvalue></defaultvalue>
				<admindefaultvalue>1,2,3,4,5,6</admindefaultvalue>
			</option>
			<option name="admin.user.canAddUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.canSearchUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.canEditUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.canEditMailAddress">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.canEditPassword">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.canDeleteUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.canBanUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.canMailUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.canAddGroup">
				<categoryname>admin.user.group</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.canDeleteGroup">
				<categoryname>admin.user.group</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.user.canManageUserOption">
				<categoryname>admin.user.option</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			
			<option name="admin.language.canManageLanguage">
				<categoryname>admin.language</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			
			<option name="admin.style.canManageStyle">
				<categoryname>admin.style</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			<option name="admin.style.canUseDisabledStyle">
				<categoryname>admin.style</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			
			<option name="admin.display.canManagePageMenu">
				<categoryname>admin.display.pageMenu</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			
			<option name="admin.template.canManageTemplate">
				<categoryname>admin.template</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
			</option>
			
			<option name="user.attachment.maxSize">
				<categoryname>user.message.attachment</categoryname>
				<optiontype>fileSize</optiontype>
				<defaultvalue>1000000</defaultvalue>
			</option>
			<option name="user.attachment.allowedExtensions">
				<categoryname>user.message.attachment</categoryname>
				<optiontype>textarea</optiontype>
				<defaultvalue><![CDATA[gif
jpg
jpeg
png
bmp
zip
txt
pdf]]></defaultvalue>
				<wildcard><![CDATA[*]]></wildcard>
			</option>
			<option name="user.attachment.maxCount">
