=== WoltLab/WCF/XSD/userNotificationEvent.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install, update or delete event listeners. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data node -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element type -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="event" type="event" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- delete element type -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="event" type="event" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- event listener element type -->
	<xs:complexType name="event">
		<xs:all>
			<xs:element name="classname" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="255" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="name" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="255" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="objecttype" type="xs:string" minOccurs="0" />
			<xs:element name="options" type="xs:string" minOccurs="0" />
			<xs:element name="permissions" type="xs:string" minOccurs="0" />
			<xs:element name="preset" type="woltlab_boolean" minOccurs="0" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/userNotificationEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/maelstrom/userNotificationEvent.xsd">
	<import>
		<event>
			<name>following</name>
			<objecttype>com.woltlab.wcf.user.follow</objecttype>
			<classname><![CDATA[wcf\system\user\notification\event\UserFollowFollowingUserNotificationEvent]]></classname>
		</event>
		
		<event>
			<name>comment</name>
			<objecttype>com.woltlab.wcf.user.profileComment.notification</objecttype>
			<classname><![CDATA[wcf\system\user\notification\event\UserProfileCommentUserNotificationEvent]]></classname>
			<preset>1</preset>
			<options>module_user_profile_wall</options>
		</event>
		<event>
			<name>commentResponse</name>
			<objecttype>com.woltlab.wcf.user.profileComment.response.notification</objecttype>
			<classname><![CDATA[wcf\system\user\notification\event\UserProfileCommentResponseUserNotificationEvent]]></classname>
			<preset>1</preset>
			<options>module_user_profile_wall</options>
		</event>
		<event>
			<name>commentResponseOwner</name>
			<objecttype>com.woltlab.wcf.user.profileComment.response.notification</objecttype>
			<classname><![CDATA[wcf\system\user\notification\event\UserProfileCommentResponseOwnerUserNotificationEvent]]></classname>
			<preset>1</preset>
			<options>module_user_profile_wall</options>
		</event>
		
		<event>
			<name>like</name>
			<objecttype>com.woltlab.wcf.user.profileComment.like.notification</objecttype>
			<classname><![CDATA[wcf\system\user\notification\event\UserProfileCommentLikeUserNotificationEvent]]></classname>
			<preset>1</preset>
			<options>module_like</options>
		</event>
		<event>
			<name>like</name>
			<objecttype>com.woltlab.wcf.user.profileComment.response.like.notification</objecttype>
			<classname><![CDATA[wcf\system\user\notification\event\UserProfileCommentResponseLikeUserNotificationEvent]]></classname>
			<preset>1</preset>
			<options>module_like</options>
		</event>
		
		<event>
			<name>comment</name>
			<objecttype>com.woltlab.wcf.moderation.queue.notification</objecttype>
			<classname><![CDATA[wcf\system\user\notification\event\ModerationQueueCommentUserNotificationEvent]]></classname>
			<preset>1</preset>
			<permissions>mod.general.canUseModeration</permissions>
		</event>
		<event>
			<name>commentResponse</name>
			<objecttype>com.woltlab.wcf.moderation.queue.response.notification</objecttype>
			<classname><![CDATA[wcf\system\user\notification\event\ModerationQueueCommentResponseUserNotificationEvent]]></classname>
			<preset>1</preset>
			<permissions>mod.general.canUseModeration</permissions>
		</event>
	</import>
</data>
